import { StyleSheet } from '@react-pdf/renderer';

import { FAMILIA_SANS, FAMILIA_SERIF } from './fuentes';
import {
  ANCHO_DEL_CENTRO,
  ANCHO_DEL_ROTULO,
  ASCENDENTE,
  CENTRO_DE_LA_MAYUSCULA,
  CENTRO_DE_LA_MINUSCULA,
  centrarMayuscula,
  COLOR,
  CUERPO,
  EJE,
  HILO,
  INTERLINEADO,
  LETRA_MAS_CHICA,
  MARGEN,
  SANGRIA,
} from './medidas';

export const ESTILOS = StyleSheet.create({
  pagina: {
    fontFamily: FAMILIA_SANS,
    fontSize: CUERPO,
    color: COLOR.ink,
    paddingTop: MARGEN,
    paddingHorizontal: MARGEN,
    paddingBottom: 84,
  },

  encabezado: { flexDirection: 'row', alignItems: 'flex-start' },
  emisor: { flexGrow: 1, flexBasis: 0 },
  marca: { fontFamily: FAMILIA_SERIF, fontSize: 21, lineHeight: 1.1 },
  lema: { fontSize: 9, lineHeight: 1.3, color: COLOR.text2, marginTop: 1 },
  datosDelTaller: { marginTop: 10 },
  datoDelTaller: { fontSize: 9, lineHeight: 1.4, color: COLOR.text2 },
  centro: { width: ANCHO_DEL_CENTRO, alignItems: 'center', marginTop: 5 },
  equis: { width: 34, height: 34, borderWidth: 1.2, borderColor: COLOR.ink, alignItems: 'center' },
  equisLetra: {
    fontSize: 21,
    lineHeight: 1,
    fontWeight: 600,
    marginTop: centrarMayuscula(34 - 2 * 1.2, 21),
  },
  leyenda: {
    marginTop: 6,
    fontSize: LETRA_MAS_CHICA,
    lineHeight: 1.3,
    fontWeight: 600,
    letterSpacing: 0.3,
    textAlign: 'center',
  },
  aclaracionDeLaLeyenda: {
    marginTop: 3,
    fontSize: LETRA_MAS_CHICA,
    lineHeight: 1.3,
    color: COLOR.text2,
    textAlign: 'center',
  },
  derecha: { flexGrow: 1, flexBasis: 0, alignItems: 'flex-end', marginTop: 5 },
  rotulo: { width: ANCHO_DEL_ROTULO, borderWidth: HILO, borderColor: COLOR.ink },
  rotuloArriba: { paddingHorizontal: 6, paddingTop: 6, paddingBottom: 7 },
  rotuloTipo: {
    fontSize: LETRA_MAS_CHICA,
    lineHeight: 1.2,
    fontWeight: 600,
    letterSpacing: 0.45,
    textTransform: 'uppercase',
  },
  numero: { fontSize: 13, lineHeight: 1.2, fontWeight: 600, marginTop: 3 },
  numeroSinAsignar: { fontSize: CUERPO, lineHeight: 1.3, color: COLOR.text2, marginTop: 4 },
  rotuloAbajo: { flexDirection: 'row', borderTopWidth: HILO, borderTopColor: COLOR.ink },
  casilla: { paddingHorizontal: 5, paddingTop: 5, paddingBottom: 6 },
  casillaConFilete: { borderLeftWidth: HILO, borderLeftColor: COLOR.ink },
  casillaTitulo: {
    fontSize: LETRA_MAS_CHICA,
    lineHeight: 1.2,
    fontWeight: 600,
    letterSpacing: 0.45,
    textTransform: 'uppercase',
    color: COLOR.text3,
  },
  casillaValor: { fontSize: 9.5, lineHeight: 1.25, fontWeight: 600, marginTop: 2 },

  datosDelTrabajo: {
    flexDirection: 'row',
    marginTop: 18,
    borderTopWidth: HILO,
    borderTopColor: COLOR.ink,
    borderBottomWidth: HILO,
    borderBottomColor: COLOR.ink,
  },
  datoDelTrabajo: { flexBasis: 0, paddingVertical: 7, paddingRight: 10 },
  datoDelTrabajoConFilete: {
    borderLeftWidth: HILO,
    borderLeftColor: COLOR.border,
    paddingLeft: 10,
  },
  datoDelTrabajoValor: { fontSize: CUERPO, lineHeight: 1.35, fontWeight: 600, marginTop: 3 },

  tituloDeSeccion: { flexDirection: 'row', alignItems: 'center', marginTop: 20, marginBottom: 8 },
  rotuloChico: {
    fontSize: LETRA_MAS_CHICA,
    lineHeight: 1.2,
    fontWeight: 600,
    letterSpacing: 0.45,
    textTransform: 'uppercase',
    color: COLOR.text2,
  },
  filete: { flexGrow: 1, marginLeft: 8, borderBottomWidth: HILO, borderBottomColor: COLOR.border },

  parrafo: { fontSize: CUERPO, lineHeight: INTERLINEADO, textAlign: 'justify' },
  renglon: { fontSize: CUERPO, lineHeight: INTERLINEADO },
  fuerte: { fontWeight: 600 },
  entrada: { fontSize: 11.5, lineHeight: 1.45, marginTop: 16 },

  marco: {
    flexDirection: 'row',
    marginTop: 16,
    paddingVertical: 9,
    paddingHorizontal: 12,
    borderWidth: HILO,
    borderColor: COLOR.border,
    borderRadius: 6,
  },
  marcoCuerpo: { flexGrow: 1, flexBasis: 0, marginLeft: 10 },
  marcoTitulo: { fontSize: CUERPO, lineHeight: INTERLINEADO, fontWeight: 600 },
  marcaDeRevision: { width: 22, height: 20.4 },
  marcaDeRevisionNumero: {
    position: 'absolute',
    left: 0,
    right: 0,
    top: 8.2,
    fontSize: 8,
    lineHeight: 1,
    fontWeight: 600,
    textAlign: 'center',
  },

  mueble: { flexDirection: 'row', paddingVertical: 8 },
  muebleConFilete: { borderBottomWidth: HILO, borderBottomColor: COLOR.hairline },
  globo: {
    width: EJE * 2,
    height: EJE * 2,
    borderRadius: EJE,
    borderWidth: 1,
    borderColor: COLOR.ink,
    alignItems: 'center',
    marginTop: CENTRO_DE_LA_MAYUSCULA - EJE,
  },
  globoNumero: {
    fontSize: 8,
    lineHeight: 1,
    fontWeight: 600,
    marginTop: centrarMayuscula(EJE * 2 - 2, 8),
  },
  muebleCuerpo: { flexGrow: 1, flexBasis: 0, marginLeft: SANGRIA - EJE * 2 },
  muebleLargo: { paddingLeft: SANGRIA, paddingBottom: 8 },

  item: { flexDirection: 'row', marginBottom: 2 },
  punto: {
    width: 3.4,
    height: 3.4,
    borderRadius: 1.7,
    backgroundColor: COLOR.ink,
    marginTop: CENTRO_DE_LA_MINUSCULA - 1.7,
    marginLeft: EJE - 1.7,
    marginRight: SANGRIA - EJE - 1.7,
  },
  tilde: {
    width: SANGRIA,
    paddingLeft: EJE - 5.25,
    paddingTop: (CENTRO_DE_LA_MAYUSCULA + CENTRO_DE_LA_MINUSCULA) / 2 - (10.5 * 11.5) / 24,
  },
  textoDeItem: { flexGrow: 1, flexBasis: 0, fontSize: CUERPO, lineHeight: INTERLINEADO },

  caja: {
    flexDirection: 'row',
    marginTop: 18,
    paddingVertical: 9,
    paddingHorizontal: 14,
    backgroundColor: COLOR.mesa,
    borderRadius: 6,
  },
  cajaRotulo: { width: 112, paddingTop: (CUERPO - LETRA_MAS_CHICA) * ASCENDENTE },
  cajaTexto: { fontSize: CUERPO, lineHeight: INTERLINEADO, fontWeight: 600 },

  valores: {
    backgroundColor: COLOR.mesa,
    borderRadius: 8,
    paddingTop: 13,
    paddingBottom: 11,
    paddingHorizontal: 16,
  },
  opcionElegida: { marginBottom: 9 },
  totalFila: { flexDirection: 'row', justifyContent: 'space-between' },
  totalEtiqueta: {
    fontSize: 12,
    lineHeight: 1.3,
    fontWeight: 600,
    marginTop: (22 - 12) * ASCENDENTE,
  },
  totalMonto: { fontSize: 22, lineHeight: 1.1, fontWeight: 600 },
  acordado: { fontSize: CUERPO, lineHeight: INTERLINEADO, fontWeight: 600, textAlign: 'right' },
  desglose: { marginTop: 9, paddingTop: 5, borderTopWidth: HILO, borderTopColor: COLOR.border },
  lineaDePuntos: { flexDirection: 'row', alignItems: 'flex-end', paddingVertical: 2 },
  puntos: {
    flexGrow: 1,
    marginHorizontal: 6,
    marginBottom: 4,
    borderBottomWidth: 0.9,
    borderBottomStyle: 'dotted',
    borderBottomColor: COLOR.text3,
  },
  cierre: { marginTop: 3, paddingTop: 3, borderTopWidth: 0.9, borderTopColor: COLOR.ink },

  tabla: {
    backgroundColor: COLOR.mesa,
    borderRadius: 8,
    paddingHorizontal: 16,
    paddingVertical: 5,
  },
  tablaFila: { flexDirection: 'row', paddingVertical: 8 },
  tablaFilaConFilete: { borderTopWidth: HILO, borderTopColor: COLOR.border },
  colOpcion: { flexGrow: 1, flexBasis: 0, paddingRight: 14 },
  colMonto: { alignItems: 'flex-end' },
  montoTotal: { fontSize: 12, lineHeight: 1.27, fontWeight: 600 },
  notaAlPie: { fontSize: 9, lineHeight: 1.45, color: COLOR.text2, marginTop: 7 },

  definiciones: { marginTop: 14 },
  definicion: { flexDirection: 'row', paddingVertical: 4 },
  definicionConFilete: { borderTopWidth: HILO, borderTopColor: COLOR.hairline },
  termino: { width: 124, paddingTop: (CUERPO - LETRA_MAS_CHICA) * ASCENDENTE },

  nota: { flexDirection: 'row', marginBottom: 5 },
  notaNumero: {
    width: EJE * 2,
    marginRight: SANGRIA - EJE * 2,
    fontSize: CUERPO,
    lineHeight: INTERLINEADO,
    fontWeight: 600,
    textAlign: 'center',
  },

  pie: {
    position: 'absolute',
    left: MARGEN,
    right: MARGEN,
    bottom: 34,
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingTop: 7,
    borderTopWidth: HILO,
    borderTopColor: COLOR.border,
  },
  pieTexto: { fontSize: 8, color: COLOR.text3 },
  cornisa: {
    position: 'absolute',
    left: MARGEN,
    right: MARGEN,
    top: 26,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-end',
  },
  cornisaMarca: { fontFamily: FAMILIA_SERIF, fontSize: 10 },
  cornisaTexto: {
    flexGrow: 1,
    flexBasis: 0,
    marginLeft: 24,
    marginBottom: 1.5,
    fontSize: 8,
    color: COLOR.text3,
    textAlign: 'right',
    maxLines: 1,
    textOverflow: 'ellipsis',
  },
  borrador: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    alignItems: 'center',
    justifyContent: 'center',
  },
  borradorTexto: {
    width: 700,
    flexShrink: 0,
    fontSize: 96,
    fontWeight: 600,
    letterSpacing: 3.8,
    textAlign: 'center',
    color: COLOR.ink,
    opacity: 0.07,
    transform: 'rotate(-35deg)',
  },
});
