export {
  aplicarPorcentaje,
  BASE_PUNTOS_BASICOS,
  centavos,
  centavosEn,
  CERO,
  esMoneda,
  esNegativo,
  importeDelTaller,
  maximo,
  minimo,
  MONEDA_DEL_TALLER,
  monedaLeida,
  MONEDAS,
  negar,
  puntosBasicos,
  restar,
  sumar,
  sumarTodos,
  type Moneda,
  type MonedaDelTaller,
  type Money,
  type PuntosBasicos,
} from './money.ts';

export {
  deLaMoneda,
  enPesos,
  esDeLaMoneda,
  plata,
  plataEn,
  sumarPlata,
  totalesPorMoneda,
  type Plata,
  type PlataEn,
  type TotalDeUnaMoneda,
} from './plata.ts';

export {
  cotizacion,
  cotizacionDelCambio,
  cotizacionLeida,
  dolaresDePesos,
  esCotizacion,
  loQueDescuenta,
  necesitaCotizacion,
  pesosDeDolares,
  RANGO_DE_LA_COTIZACION,
  totalEnPesos,
  totalQueDescuenta,
  valorEnPesos,
  type Cotizacion,
  type ImporteDeUnPago,
} from './cotizacion.ts';

export {
  esIdioma,
  ETIQUETAS_DE_IDIOMA,
  etiquetaDelIdioma,
  IDIOMA_BASE,
  idiomaDeLaEtiqueta,
  idiomaDelNavegador,
  idiomaLeido,
  IDIOMAS,
  type Idioma,
} from './idioma.ts';

export { calcularDistribucion, DIEZMO, type Distribucion, type EntradaCascada } from './cascada.ts';

export {
  admiteLaMeta,
  type AjustesDelReparto,
  type AjustesDeSiempre,
  type AporteDelMes,
  aportesDelReparto,
  type BaseDeLaObligacion,
  BASES_DE_OBLIGACION,
  calcularPorLaFila,
  cambiarElPaso,
  cambiarLaClase,
  cambiarLaObligacion,
  cambiarLaParte,
  type CambioDeLaFila,
  cambiosDeLaFila,
  type ClaseDePaso,
  CLASES_DE_PASO,
  type Cobertura,
  columnasDeSiempre,
  type ColumnasDeSiempre,
  conDesde,
  type DatosDelMes,
  type EntradaDeLaLiquidacion,
  type EntradaDelReparto,
  esDeLaMonedaDelTaller,
  esDiaDePago,
  type Fila,
  filaDelMes,
  type FilaDelMes,
  filaDeSiempre,
  type GastoDeUnTesoro,
  LARGO_MAXIMO_DEL_RENGLON,
  leerLaFila,
  type LiquidacionDelMes,
  type LiquidacionPorLaFila,
  loDelMes,
  loVistoEsOtro,
  lugarLibreDelReparto,
  type MetaDelMes,
  type ModoDePaso,
  modoInicial,
  MODOS_DE_PASO,
  modosPosibles,
  MONTO_MAXIMO_DE_LA_FILA,
  moverObligacion,
  moverPaso,
  type ObligacionDeLaFila,
  type ObligacionDelMes,
  type ObligacionDelPlan,
  type ObligacionRepartida,
  type ParteDelMes,
  type ParteDelReparto,
  type ParteRepartida,
  type PasoDeLaFila,
  type PasoDelMes,
  type PasoDelPlan,
  type PasoLiquidado,
  type PasoRepartido,
  planDeLaLiquidacion,
  planDelReparto,
  type PlanDelReparto,
  ponerDespues,
  ponerElSuperavit,
  ponerEnElReparto,
  ponerObligacion,
  ponerPaso,
  previoDeLoVisto,
  type PrevioDelReparto,
  previoDelMes,
  previoQueVio,
  primerProblemaDeLaFila,
  type ProblemaDeLaFila,
  type ProblemaEnLaFila,
  problemasDeLaFila,
  type Renglon,
  repartir,
  type Reparto,
  type RepartoDelCobro,
  repartosDelCobro,
  sacarDeLaFila,
  sumaDelReparto,
  type SuperavitDelMes,
  type TesoroDeLaFila,
  tesorosDeLaFila,
  type TesorosDelSistema,
  type TipoDelPaso,
  type TipoDeTesoro,
  tipoDelPaso,
  tipoDelTesoro,
  TIPOS_DE_TESORO,
  TOPE_DE_OBLIGACIONES,
  TOPE_DE_PARTES,
  TOPE_DE_PASOS,
  TOPE_DE_RENGLONES,
  ULTIMO_DIA_DE_PAGO,
  type VencimientoDelMes,
  vencimientosDelPaso,
} from './fila.ts';

export {
  calcularMargen,
  calcularMargenEnDolares,
  CATEGORIAS_DE_COSTO,
  categoriasEstimadas,
  costoEstimado,
  costosEnDolares,
  SIN_ESTIMAR,
  type CategoriaDeCosto,
  type CostosEstimados,
  type EntradaDelMargen,
  type EntradaDelMargenEnDolares,
  type MargenDelTrabajo,
  type MargenEnDolares,
} from './costos.ts';

export {
  CANTIDAD_MAXIMA,
  cantidadEditada,
  cantidadEscrita,
  catalogoDeNecesidades,
  claveDelNombre,
  cuentaDeLoQueHaceFalta,
  esNombreDeNecesidad,
  LARGO_MAXIMO_DEL_NOMBRE,
  nombreEditado,
  nombreEscrito,
  segmentosDeLoQueHaceFalta,
  sugerenciasDeNecesidad,
  SUGERENCIAS_MAXIMAS,
  TIPOS_DE_NECESIDAD,
  type CuentaDeLoQueHaceFalta,
  type NecesidadUsada,
  type NombreDelCatalogo,
  type ParaContar,
  type SegmentoDeLoQueHaceFalta,
  type TipoDeNecesidad,
} from './necesidades.ts';

export {
  claveBancariaDe,
  digitosDeCbu,
  esClaveVirtual,
  esCuentaDeMercadoPago,
  esLinkDeMercadoPago,
  formatearCbu,
  HOSTS_DE_MERCADO_PAGO,
  LARGO_DE_CBU,
  LARGO_MAXIMO_DE_ALIAS,
  LARGO_MAXIMO_DEL_LINK,
  LARGO_MINIMO_DE_ALIAS,
  normalizarAlias,
  normalizarLinkDeCobro,
  PREFIJO_DE_MERCADO_PAGO,
  revisarAlias,
  revisarCbu,
  revisarLinkDeCobro,
  verificadorDelBloque,
  type AvisoDeAlias,
  type ClaveBancaria,
  type MotivoDeAlias,
  type MotivoDeCbu,
  type MotivoDelLink,
  type RevisionDeAlias,
  type RevisionDeCbu,
  type RevisionDelLink,
} from './cobro.ts';

export {
  digitosDeCuit,
  formatearCuit,
  LARGO_DE_CUIT,
  PREFIJOS_DE_EMPRESA,
  PREFIJOS_DE_PERSONA,
  revisarCuit,
  verificadorDeCuit,
  type MotivoDeCuit,
  type RevisionDeCuit,
} from './cuit.ts';

export {
  calcularLiquidacion,
  liquidadoDelMes,
  planDeLiquidacion,
  resumenDelMes,
  SIN_DIEZMO,
  sueldoDelMes,
  topesDeLaLiquidacion,
  type AjustesDeLiquidacion,
  type EntradaLiquidacion,
  type EscalonDelMes,
  type Liquidacion,
  type LiquidacionRegistrada,
  type LiquidadoDelMes,
  type Objetivos,
  type PlanDeLiquidacion,
  type Reapertura,
  type ResumenDelMes,
  type SueldoDelMes,
  type Topes,
} from './liquidacion.ts';

export {
  calcularSena,
  porcentajeDeLaSena,
  SENA_HABITUAL,
  type EntradaDeLaSena,
  type SenaDelTrabajo,
} from './sena.ts';

export {
  conLaForma,
  formasDeCobro,
  FORMAS_DE_COBRO,
  instanciasPendientes,
  INSTANCIAS_DE_PAGO,
  montoParaPegar,
  ofrece,
  pagoQueToca,
  pagosPorDelante,
  unaSolaForma,
  type FormaDeCobro,
  type InstanciaDePago,
  type PagoPorDelante,
} from './pagos.ts';

export {
  comoPagar,
  estaAprobada,
  hayComoTransferir,
  HITOS_DEL_CAMINO,
  llegoAl,
  notaDelRelevamiento,
  proyeccionDeLaEntrega,
  relevamientoDelTrabajo,
  textoDeLaProyeccion,
  tuvoEstimativo,
  vistaDelCliente,
  type ArchivoDelCliente,
  type CobroDelTaller,
  type ComoPagar,
  type ComprometidaDelTrabajo,
  type CoordinacionDeLaEntrega,
  type CuentaParaTransferir,
  type DatosDelTrabajo,
  type DiaQueLeQuedaBien,
  type EntregaDelTrabajo,
  type EntregaQueSeCoordina,
  type EstadoDelHito,
  type EstadoDelRelevamiento,
  type EtapaAprobada,
  type EtapaDeLaVista,
  type EventoDelCliente,
  type FechasDelTrabajo,
  type FocoDeLaVista,
  type FormatosDeFecha,
  type HitoDelTrabajo,
  type HitoDeLaVista,
  type NotaDelRelevamiento,
  type PagoDelCliente,
  type PagoOfrecido,
  type PagoPendiente,
  type PagoQueSigue,
  type PresupuestoAceptado,
  type PresupuestoDelTrabajo,
  type PresupuestoDeLaVista,
  type PresupuestoMandado,
  type PropuestaDeEntrega,
  type ProyeccionDeLaEntrega,
  type RelevamientoDeLaVista,
  type RelevamientoPorHacer,
  type RespuestaDelCliente,
  type SenaDeLaVista,
  type TextosDeComoPagar,
  type TextosDeLaNota,
  type TextosDeLaNotaEnSuEstado,
  type TextosDeLaProyeccion,
  type TextosDeLaVista,
  type TextosDeLosEventos,
  type TextosDelHito,
  type TitularDeLaVista,
  type TrabajoDelCliente,
  type VisitaDelTrabajo,
  type VistaAntesDelPresupuesto,
  type VistaAprobada,
  type VistaDelCliente,
  type VistaEsperandoLaSena,
} from './vistaCliente.ts';

export {
  EN_SEGUIMIENTO,
  ESTADOS,
  ESTADOS_DE_CONSULTA,
  esEstado,
  esEstadoDeConsulta,
  estaLiquidado,
  faseDe,
  puedeCambiarEstado,
  puedeCerrarPerdido,
  puedeCobrar,
  puedeLiquidar,
  puedePasarASeguimiento,
  puedeReabrir,
  puedeReactivar,
  puedeRevertir,
  TRANSICIONES,
  type EstadoDeConsulta,
  type EstadoLiquidado,
  type EstadoProyecto,
  type Fase,
} from './estados.ts';

export {
  DIAS_HABILES_DE_ENTREGA,
  DIAS_HABILES_PARA_PRESUPUESTAR,
  diaDeLaSemana,
  diaDelMes,
  diasEntre,
  entregaEstimada,
  esFechaQueExiste,
  esMes,
  mesDe,
  mesesDelRango,
  sumarDias,
  sumarDiasHabiles,
  sumarMeses,
  vencimientoDelPresupuesto,
} from './fechas.ts';

export {
  analisisDeEntregas,
  cuentaDe,
  DIAS_DE_ACIERTO,
  fraseDeLasCumplidas,
  fraseDeLosAciertos,
  fraseDelDesvio,
  resumirDias,
  SIN_TIPO,
  UMBRAL_CUENTAS,
  UMBRAL_MEDIANA,
  UMBRAL_PORCENTAJE,
  type AnalisisDeEntregas,
  type CambioDeFechaParaElAnalisis,
  type Cuenta,
  type FilaDelAnalisis,
  type GrupoPorCarga,
  type GrupoPorTipo,
  type OrigenDeLaFecha,
  type PrecisionDeLasEntregas,
  type ResumenDeDias,
  type TipoDeFecha,
  type TrabajoParaElAnalisis,
} from './analitico.ts';

export {
  armarRespuestaDeEntrega,
  DESDE_CUANTOS_DIAS,
  DIAS_MAXIMOS_DE_LA_RESPUESTA,
  esDiaDeLaEntrega,
  esFranja,
  FORMAS_DE_COORDINAR,
  FRANJAS_DE_ENTREGA,
  HASTA_CUANTOS_DIAS,
  LARGO_MAXIMO_DE_LA_NOTA,
  MOTIVOS_DE_LA_ENTREGA,
  RESPUESTAS_DE_ENTREGA,
  sePuedeElegir,
  validarRespuestaDeEntrega,
  type DiaElegido,
  type FormaDeCoordinar,
  type FranjaDeEntrega,
  type MotivoDeLaEntrega,
  type MotivoDeLaValidacion,
  type RespuestaDeEntrega,
  type RespuestaDeEntregaParaMandar,
} from './entrega.ts';

export {
  DIAS_QUE_VALE_UN_PRESUPUESTO,
  seMandaElPresupuesto,
  vencioElPresupuesto,
  vigenciaAlMandar,
} from './vigencia.ts';

export {
  abonadoEn,
  acordadoAlAprobar,
  borradorNuevo,
  CAMPOS_QUE_FALTAN,
  CLAUSULAS_DE_LA_MONEDA_DE_SIEMPRE,
  clausulaDeLaMonedaDelTrabajo,
  COBROS_POSIBLES,
  cobraEnLeido,
  COMBINACIONES_DE_LA_MONEDA,
  combinacionDeLaMoneda,
  completarHuecos,
  CONDICIONES_FISCALES,
  cuentasDelPresupuesto,
  documentoDelPresupuesto,
  LARGO_DE_LA_CLAUSULA_DEL_DOCUMENTO,
  modificacionDelPresupuesto,
  monedaDeLoAbonado,
  monedaDeLoAbonadoDelDocumento,
  monedaDelDocumento,
  type ClausulasDeLaMoneda,
  type CombinacionDeLaMoneda,
  type DocumentoEnDolares,
  type DocumentoEnPesos,
  type ModificacionDelBorrador,
  type ReferenciaEnPesos,
  esIdDelPresupuesto,
  esNumeroDePresupuesto,
  GRUPOS_DE_CLAUSULAS,
  hayCambiosSinMandar,
  HUECOS,
  huecosDelPresupuesto,
  IMPORTE_MAXIMO_DEL_PRESUPUESTO,
  LARGOS_DEL_DOCUMENTO,
  LARGOS_DEL_PRESUPUESTO,
  leerBorrador,
  leerDocumento,
  leerPlantilla,
  letraDeLaOpcion,
  mensajeParaElTaller,
  MOTIVOS_DE_LO_QUE_FALTA,
  NOMBRE_DE_LA_CONDICION,
  nombreDelArchivo,
  numeroVisible,
  PLANTILLA_DE_SIEMPRE,
  PLANTILLAS_DE_SIEMPRE,
  plantillaDeSiempre,
  plantillaDelTaller,
  plazoDelPresupuesto,
  problemaDeLaPlantilla,
  problemaDelBorrador,
  problemaDelDocumento,
  problemasParaMandar,
  RANGOS_DEL_PRESUPUESTO,
  recortado,
  resumenDeLosValores,
  soloLaAceptada,
  textoDeLaForma,
  textoDeLaGarantia,
  tildadasPorDefecto,
  tituloDelArchivo,
  TOPES_DEL_PRESUPUESTO,
  totalPropuesto,
  usaElHueco,
  valoresDelTrabajo,
  type BorradorDelPresupuesto,
  type CampoQueFalta,
  type Clausula,
  type CondicionFiscal,
  type CuentaDeUnValor,
  type DatosDelTaller,
  type DocumentoDelPresupuesto,
  type EntradaDelBorradorNuevo,
  type EntradaDelDocumento,
  type EntradaDeLosHuecos,
  type FormaDePago,
  type FormaElegida,
  type Formatos,
  type FrasesConNumero,
  type FrasesDelNumero,
  type GrupoDeClausulas,
  type HerrajesDelBorrador,
  type Hueco,
  type LoQueFalta,
  type MotivoDeLoQueFalta,
  type Mueble,
  type MuebleDelDocumento,
  type OpcionDelDocumento,
  type OpcionDelTrabajo,
  type PlantillaDelPresupuesto,
  type ProblemaDeLaPlantilla,
  type ProblemaDelDocumento,
  type ProblemaDelPresupuesto,
  type Propia,
  type Seleccion,
  type TextoConTitulo,
  type ValoresDelPresupuesto,
} from './presupuesto.ts';

export {
  fechaDelPlazo,
  PLAZOS_DEL_SEGUIMIENTO,
  plazoDeLaFecha,
  RESULTADOS_DEL_CONTACTO,
  type PlazoDelSeguimiento,
  type ResultadoDelContacto,
} from './seguimiento.ts';

export {
  ANTICIPACIONES,
  AVISO_DE_LA_CATEGORIA,
  AVISOS_DE_LA_AGENDA,
  CATEGORIA_DEL_VENCIMIENTO,
  CATEGORIAS_DE_AGENDA,
  CATEGORIAS_DEL_TRABAJO,
  CATEGORIAS_DERIVADAS,
  CATEGORIAS_PROPIAS,
  diaPorHoras,
  eventosDeLaAgenda,
  eventosParaAvisar,
  horaDelEvento,
  HORARIO_DEL_TALLER,
  PREFERENCIAS_INICIALES,
  puedeArrastrarse,
  rangoQueEntra,
  TODO_EL_RELOJ,
  vencimientosDeLaFila,
  type Anticipacion,
  type AnotacionDeLaAgenda,
  type AvisoDeLaAgenda,
  type CategoriaDeAgenda,
  type CategoriaDelTrabajo,
  type CategoriaDelVencimiento,
  type CategoriaDerivada,
  type CategoriaPropia,
  type ClienteDeLaAgenda,
  type DatosDeLaAgenda,
  type DiaPorHoras,
  type EntradaDeLosVencimientos,
  type EventoDeLaAgenda,
  type EventoDerivado,
  type EventoPropio,
  type EventoVencimiento,
  type FranjaDelDia,
  type PreferenciaDeAviso,
  type PreferenciasDeAvisos,
  type ProximoDeLaAgenda,
  type ProyectoDeLaAgenda,
  type RangoDeHoras,
  type RangoDeLaAgenda,
  type RangoDeMeses,
  type VencimientoDeLaAgenda,
} from './agenda.ts';

export {
  comoGuardar,
  comoLaVeElCliente,
  duracion,
  elMueble,
  encuestaBase,
  enPalabras,
  envioDe,
  ESCALA_POR_DEFECTO,
  ESCALAS,
  estadoDelPedido,
  fueMandado,
  LARGO_MAXIMO_DE_LA_OPCION,
  LARGO_MAXIMO_DE_LA_PREGUNTA,
  LIMITE_DEL_LARGO_SEG,
  limpiarBorrador,
  lineasDeLaRespuesta,
  MAXIMO_DE_OPCIONES,
  menosDeMinutos,
  mesesDeHistoria,
  MINIMO_DE_OPCIONES,
  mismaForma,
  modoDeMostrar,
  pasoDe,
  pasosDe,
  pedidosPorTrabajo,
  primeraPalabra,
  promedio,
  propiasDelTrabajo,
  PUNTOS_DE_LA_TASA,
  queTieneLaEncuesta,
  REFERENCIA_SEG,
  resumenDeOpiniones,
  revisarBorrador,
  SEGUNDOS_DE_ENTRADA,
  SEGUNDOS_POR_TIPO,
  sePuedeBorrar,
  TIPOS_DE_PREGUNTA,
  TIPOS_DE_PREGUNTA_PROPIA,
  TOPE_PREGUNTAS,
  TOPE_PROPIAS,
  UMBRAL_BARRAS,
  UMBRAL_EVOLUCION,
  UMBRAL_MESES,
  usoDeLasPreguntas,
  versionesDe,
  vigentesPorSerie,
  type Cara,
  type Comentario,
  type ComoGuardar,
  type Conteo,
  type DatosDeLasOpiniones,
  type Duracion,
  type EncuestaBase,
  type EncuestaGuardada,
  type EnvioDelTrabajo,
  type Escala,
  type EstadoDelPedido,
  type Evolucion,
  type FilaDeTrabajo,
  type FormaDePregunta,
  type Genero,
  type LineaDeLaRespuesta,
  type LoQueTieneLaEncuesta,
  type ModoDeMostrar,
  type Paso,
  type PedidoMandado,
  type Polo,
  type PreguntaDeLaEncuesta,
  type PreguntaEditable,
  type PreguntaGuardada,
  type ProblemaDelBorrador,
  type Promedio,
  type PuntoDeLaEvolucion,
  type RenglonGuardado,
  type RespuestaGuardada,
  type ResultadoDePregunta,
  type ResumenDeOpiniones,
  type Situacion,
  type TextosDeLaEscala,
  type TextosDeLasEscalas,
  type TextosDelPaso,
  type TipoDePregunta,
  type TipoDePreguntaPropia,
  type TonoDelLargo,
  type TrabajoOpinado,
  type UsoDeLaPregunta,
  type ValorDeLaEscala,
  type ValorDeSiTalVezNo,
  type ValorGuardado,
  type VersionAnterior,
} from './opiniones.ts';

export {
  armarRespuesta,
  esLinkDeResena,
  faltantes,
  HOSTS_DE_RESENA,
  largoDelTexto,
  LARGO_MAXIMO_DE_LA_RESPUESTA,
  LARGO_MAXIMO_DEL_LINK_DE_RESENA,
  MOTIVOS_DEL_RECHAZO,
  normalizarLinkDeResena,
  revisarLinkDeResena,
  sinBlancosEnLasPuntas,
  tieneTexto,
  validarRespuesta,
  type MotivoDelLinkDeResena,
  type MotivoDelRechazo,
  type RenglonDelFormulario,
  type RespuestaDelFormulario,
  type RevisionDelLinkDeResena,
  type ValorDelFormulario,
  type ValoresDelFormulario,
} from './encuesta.ts';

export {
  asientosDeLaLinea,
  asientosDelLibro,
  asientosDelMes,
  CATEGORIA_DE_APERTURA,
  enLaMonedaDelTaller,
  entradasYSalidas,
  entradasYSalidasPorId,
  esAnteriorALaApertura,
  estadoDelDiezmo,
  fechaDeApertura,
  lineasDelLibro,
  mueveLosTesoros,
  proyeccionCocos,
  saldosDelLibro,
  saldosDelLibroPorId,
  saldosPorId,
  saldosPorTesoro,
  TESOROS,
  type Asiento,
  type DatosDelLibro,
  type EntradasYSalidas,
  type EstadoDelDiezmo,
  type GastoDelLibro,
  type LineaDelLibro,
  type MovimientoDelLibro,
  type OrigenDeAsiento,
  type PagoDelLibro,
  type ProyectoDelLibro,
  type RepartoDelLibro,
  type SaldosPorId,
  type SaldosPorTesoro,
  type SituacionDelDiezmo,
  type Tesoro,
  type TesoroDelLibro,
} from './libroMayor.ts';
export {
  comoSeMuestraLaRed,
  enOrden,
  esLinkDeFacebook,
  esLinkDeInstagram,
  esLinkDeLaRed,
  esLinkDeTiktok,
  formaCortaDeLaRed,
  hayAlgoEnLaVidriera,
  lugaresLibres,
  moverEnLaVidriera,
  normalizarLaRed,
  ordenAlFinal,
  redesALaVista,
  redParaCompartir,
  REDES_DEL_TALLER,
  revisarFacebook,
  revisarInstagram,
  revisarLaRed,
  revisarTiktok,
  SEGMENTOS_QUE_NO_SON_UN_PERFIL,
  TOPE_DE_LA_VIDRIERA,
  VIDRIERA_VACIA,
  type CambioDeOrden,
  type FilaEnLaVidriera,
  type FotoDeLaVidriera,
  type HaciaDondeSeMueve,
  type MotivoDeLaRed,
  type RedALaVista,
  type RedDelTaller,
  type RedesDelTaller,
  type RevisionDeLaRed,
  type VidrieraDelTaller,
} from './vidriera.ts';
