import type { Mensajes } from '../es';

import { plural } from './plural';

export const editarProyecto = {
  pantalla: {
    precioEn: 'Price in',
    monedas: { ARS: 'Pesos', USD: 'Dollars' },
    laMonedaSeElige: 'The currency is chosen while the job is an inquiry.',
    cancelar: 'Cancel',
    proyectoNuevo: 'New job',
    editarProyecto: 'Edit job',
    trabajo: 'Job',
    trabajoEjemplo: '3-door wardrobe, kitchen countertop…',
    tipo: 'Job type',
    tipoEjemplo: 'Kitchen, wardrobe, walk-in closet…',
    tipoAyuda: 'With the type, Delivery insights shows you how long each kind of piece takes you.',
    presupuesto: 'Quote',
    sinDefinir: 'Not set',
    presupuestoDeLaOpcion:
      'It comes from the option you check below. To type it in yourself, remove the options.',
    presupuestoVacio: "Leave it empty until it's quoted.",
    senaPropia: 'Custom deposit (%)',
    senaDelTaller: "The shop's default",
    senaAyuda:
      "Leave it empty to ask for the usual deposit. Fill it in only if you're asking this client for a different one.",
    formaDePago: 'Payment method',
    fechaDeInicio: 'Start date',
    entregaEstimada: 'Estimated delivery',
    entregaCalculada: 'Set to 21 business days from the start.',
    horaDeLaEntrega: 'Delivery time',
    horaAyuda: 'Optional. With a time, the delivery shows up in its slot on the calendar.',
    estado: 'Status',
    estadoCongelado: {
      cobrado: 'A paid job has its split locked: reopen it to change its status.',
      perdido: 'A lost job has its split locked: reopen it to change its status.',
    },
    direccionDeEntrega: 'Delivery address',
    usarLaDelCliente: "Use the client's",
    direccionEjemplo: 'Street and number, city',
    abrirLaDireccion: 'Open the address on the map',
    comprobante: 'Invoice to issue',
    porLaCondicion: (condicion) => `Tax status: ${condicion}`,
    notasDeObra: 'Job notes',
    notasEjemplo: "Measurements, what's missing, what to discuss with the client…",
    repartoCerrado: {
      cobrado:
        "This job is paid and its split is closed: its payments and expenses can't be changed.",
      perdido:
        "This job is lost and its split is closed: its payments and expenses can't be changed.",
    },
    reactivarlo: 'Reactivate it to edit',
    reabrirElCobro: 'Reopen the payment to fix it',
    alGuardarLoCierra:
      'The fields unlock right here. Saving takes you back to close it again, with the deposit split counting what you added.',
    alGuardarLoCobra:
      'The fields unlock right here. Saving takes you back to collect it again, with the split redone.',
    totales: {
      presupuesto: 'Quote',
      cobrado: 'Collected',
      saldo: 'Balance',
      neta: 'Net',
    },
    guardarProyecto: 'Save job',
    guardarLosCambios: 'Save changes',
  },
  cambiarLaMoneda: {
    titulo: { ARS: 'Switch the job to pesos', USD: 'Switch the job to dollars' },
    bajada: "Estimated costs don't change: they're always in pesos.",
    losImportes: 'The amounts you already entered',
    pasarlos: {
      ARS: 'Convert them to pesos at this rate',
      USD: 'Convert them to dollars at this rate',
    },
    dejarlosEnBlanco: 'Leave them blank',
    losPagosEnPesos: 'Payments in pesos',
    pagoEnPesos: (concepto, monto) => `${concepto}: the client paid ${monto} in pesos.`,
    aQueDolar: 'What dollar rate applies?',
    presupuestoEnLaOtraMoneda: {
      ARS: 'The quote you sent is in pesos: send a new one.',
      USD: 'The quote you sent is in dollars: send a new one.',
    },
    cambiar: 'Change currency',
    cancelar: 'Cancel',
  },
  filas: {
    pagos: {
      titulo: 'Payments received',
      detalle: (fila) => `Description of payment ${String(fila)}`,
      quitar: (fila) => `Remove payment ${String(fila)}`,
      placeholder: 'Deposit, advance, balance…',
      agregar: 'Add a payment',
      ayuda: "What the client paid you for this job. It goes into the shop's cash.",
      vacio: "You haven't collected anything for this job yet. The deposit usually comes first.",
    },
    gastos: {
      titulo: 'Expenses and supplies',
      detalle: (fila) => `Description of expense ${String(fila)}`,
      quitar: (fila) => `Remove expense ${String(fila)}`,
      placeholder: 'Melamine, hardware, freight…',
      agregar: 'Add an expense',
      ayuda: "Materials and purchases for this piece. They're deducted from the job's income.",
      vacio: "You haven't added any expenses for this piece yet.",
      categoria: (fila) => `Category of expense ${String(fila)}`,
      sinElegir: 'Not chosen',
    },
    fecha: (fila) => `Date ${String(fila)}`,
    monto: (fila) => `Amount ${String(fila)}`,
    quiteLaFila: 'Removed the row.',
    quite: (quitado) => `Removed ${quitado}.`,
    deshacer: 'Undo',
  },
  opciones: {
    titulo: 'Options you offered',
    aprobada: (monto) => `Approved: ${monto}`,
    ayuda:
      "The quotes you offered. Check the one the client approved, and it becomes the job's quote.",
    agregar: 'Add an option',
    sinOpciones: "No options. If you're giving a single price, enter it above in Quote.",
    queIncluye: (opcion) => `What option ${String(opcion)} includes`,
    queIncluyeEjemplo: 'Just the desk, both desks…',
    estaAprobada: 'Approved',
    laAprobo: 'Approve',
    importe: (opcion) => `Amount for option ${String(opcion)}`,
    quitar: (opcion) => `Remove option ${String(opcion)}`,
    quiteLaOpcion: 'Removed the option.',
    quite: (quitado) => `Removed ${quitado}.`,
    deshacer: 'Undo',
  },
  opcionesDelTrabajo: {
    titulo: 'Quote options',
    cargarLaPrimera:
      'If you offer more than one version, add each with its amount. When the client chooses, check the one they approved.',
    cargarLasOpciones: 'Add the options',
    aprobaste: (monto) => `You approved ${monto}: it's now the job's quote.`,
    sacasteLaAprobacion: 'You removed the approval: the job has no quote now.',
    deshacer: 'Undo',
    cuantas: (opciones) => plural(opciones, { one: '# option', other: '# options' }),
    sinAprobar: "Check the one the client approved, and that amount becomes the job's quote.",
    conAprobada: "The ones they didn't choose stay here, so you know what you offered.",
    sinDetalle: 'Option with no details',
    esElPresupuesto: "Approved: it's the job's quote",
    estaAprobada: 'Approved',
    laAprobo: 'Approve',
  },
  borrado: {
    borrar: 'Delete',
    pregunta: (trabajo) => `Delete “${trabajo}”?`,
    sinPlataDelContacto: 'It has no deposit or expenses, so no money moves.',
    sinPlataDelProyecto: 'It has no payments or expenses, so no money moves.',
    conPlata: (pagos, gastos) =>
      `It'll take its ${plural(pagos, { '=0': 'no payments', one: '# payment', other: '# payments' })} and ${plural(gastos, { '=0': 'no expenses', one: '# expense', other: '# expenses' })} with it, and they'll come off the ledger.`,
    cancelar: 'Cancel',
    borrarElContacto: 'Delete contact',
    borrarElProyecto: 'Delete job',
  },
  avance: {
    titulo: 'To do',
    yaEstaListo: 'Mark as ready',
    todaviaNoEstaListo: 'Mark as not ready',
  },
  loQueHaceFalta: {
    titulo: "What's needed",
    ayuda:
      "The materials and hardware to order, and the tools to have on hand the day you do it. You'll get suggestions from what you've used before.",
    todoListo: 'all set',
    listas: (listas, cuantas) => `${String(listas)} of ${String(cuantas)}`,
    cosas: (cosas) => plural(cosas, { one: '# item', other: '# items' }),
    cerrado: 'This job is closed: the list stays as it was.',
    saque: (necesidad) => `Removed ${necesidad} from the list.`,
    deshacer: 'Undo',
    loQueMasUsas: 'What you use most',
    yaLoUsasteAntes: "You've used it before",
    trabajos: (trabajos) => plural(trabajos, { one: '# job', other: '# jobs' }),
    cantidadDe: (necesidad) => `Quantity of ${necesidad}`,
    nombreDe: (necesidad) => `Name of ${necesidad}`,
    sacarDeLaLista: (necesidad) => `Remove ${necesidad} from the list`,
  },
} satisfies Mensajes['editarProyecto'];
