import type { Mensajes } from '../es';

export const editarCliente = {
  editar: 'Edit client',
  nuevo: 'New client',
  nombre: 'Name',
  comoLoTenesAgendado: 'As saved in your contacts',
  telefono: 'Phone',
  zona: 'Area',
  localidadOBarrio: 'Town or neighborhood',
  email: 'Email',
  opcional: 'Optional',
  direccion: 'Address',
  calleYNumero: 'Street and number, town',
  comoLlego: 'How they found you',
  sinEspecificar: 'Not specified',
  quienLoRefirio: 'Who referred them',
  detalle: 'Details',
  nombreDeQuienLoRecomendo: 'Name of who recommended them',
  loQueQuierasAnotar: 'Anything you want to note',
  condicionFrenteAlIva: 'VAT status',
  condicionYComprobante: (condicion, comprobante) => `${condicion}. You issue a ${comprobante}.`,
  razonSocial: 'Legal name',
  siFacturaAUnaEmpresa: 'If you invoice a company',
  domicilioFiscal: 'Tax address',
  siEsDistinto: "If it's different from the address",
  notas: 'Notes',
  loQueConvengaRecordar: 'Anything worth remembering about this client',
  cancelar: 'Cancel',
  guardarLosCambios: 'Save changes',
  guardarCliente: 'Save client',
} satisfies Mensajes['editarCliente'];
