import type { Mensajes } from '../es';

export const movimiento = {
  dolares: 'Dollars',
  grupos: {
    ingreso: 'Income',
    gasto: 'Expense',
    diezmo: 'Tithe',
    cocos: 'Cocos',
    entre: 'Between buckets',
    dolares: 'Dollars',
  },
  clases: {
    ingresoHogar: {
      etiqueta: 'Household income',
      corta: 'To the household',
      ejemplo: 'September teaching',
    },
    ingresoMaun: {
      etiqueta: 'Shop income',
      corta: 'To the shop',
      ejemplo: 'Sold melamine offcuts',
    },
    gastoHogar: {
      etiqueta: 'Household expense',
      corta: 'From the household',
      ejemplo: 'Groceries, power and gas, pediatrician…',
    },
    gastoMaun: {
      etiqueta: 'Shop expense',
      corta: 'From the shop',
      ejemplo: 'Rent, saw blade, insurance…',
    },
    gastoTesoro: {
      etiqueta: 'Bucket expense',
      corta: 'From a bucket',
      ejemplo: 'September rent',
    },
    pagoDiezmo: {
      etiqueta: 'Tithe payment',
      corta: 'Tithe payment',
      ejemplo: 'September tithe',
    },
    aporteCocos: {
      etiqueta: 'From the shop to Cocos',
      corta: 'Contribution',
      ejemplo: "This month's contribution",
    },
    retiroCocos: {
      etiqueta: 'From Cocos to the shop',
      corta: 'Withdrawal',
      ejemplo: 'Withdrawal to buy a new machine',
    },
    gastoCocos: {
      etiqueta: 'Expense from Cocos',
      corta: 'Expense',
      ejemplo: 'Deposit on the land',
    },
    entreTesoros: {
      etiqueta: 'Between buckets',
      corta: 'Between buckets',
      ejemplo: "For this month's materials",
    },
    compraDeDolares: {
      etiqueta: 'Dollar purchase',
      corta: 'Buy',
      ejemplo: "This month's savings",
    },
    ventaDeDolares: {
      etiqueta: 'Dollar sale',
      corta: 'Sell',
      ejemplo: 'To pay the rent',
    },
    ingresoEnDolares: {
      etiqueta: 'Dollar income',
      corta: 'Income',
      ejemplo: 'Dollars I already had',
    },
  },
  categorias: {
    Docencia: 'Teaching',
    Changas: 'Odd jobs',
    Regalos: 'Gifts',
    'Venta personal': 'Personal sale',
    'Cobro suelto': 'One-off payment',
    'Venta de sobrantes': 'Leftover sales',
    Supermercado: 'Groceries',
    Servicios: 'Utilities',
    Salud: 'Health',
    Educación: 'Education',
    Transporte: 'Transportation',
    Ropa: 'Clothing',
    Recreación: 'Leisure',
    Iglesia: 'Church',
    Materiales: 'Materials',
    Herramientas: 'Tools',
    'Costos fijos': 'Fixed costs',
    'Gasto fijo': 'Fixed cost',
    Flete: 'Freight',
    'Servicios del taller': 'Shop utilities',
    Publicidad: 'Advertising',
    Compra: 'Purchase',
    Imprevisto: 'Unexpected expense',
    Regalo: 'Gift',
    'Compra del inmueble': 'Property purchase',
    'Escritura y sellos': 'Deed and stamp tax',
    Mudanza: 'Moving',
    Oficial: 'Official',
    MEP: 'MEP',
    Blue: 'Blue',
    Cripto: 'Crypto',
    'Ahorro previo': 'Earlier savings',
    Otro: 'Other',
    Cobro: 'Payment',
    Distribución: 'Split',
    Apertura: 'Starting balances',
    Ajuste: 'Adjustment',
    'Archivo de un tesoro': 'Bucket archiving',
    'Cubrir el mes': 'Covering the month',
  },
  ayuda: {
    ingresoHogar: 'Goes into the household, without going through the shop or the tithe.',
    ingresoMaun:
      "Goes into the shop's cash. This is for a one-off payment: money from a job you've added goes on that job, so it stays tied to its split.",
    gastoHogar: 'Comes out of the household.',
    gastoMaun:
      "Comes out of the shop's cash. If it's for a specific piece of furniture, add it as a job expense instead, so it comes off that job's income.",
    pagoDiezmo: 'Comes out of what the tithe has set aside.',
    aporteCocos: "Moves from the shop's cash into Cocos.",
    retiroCocos:
      "Comes out of Cocos and goes back to the shop's cash: it doesn't leave the shop, it just changes pockets.",
    gastoCocos: 'Comes out of Cocos and is spent.',
    gastoTesoro: (tesoro) => `Comes out of ${tesoro} and is spent.`,
    gastoTesoroSinElegir: 'Comes out of the bucket you pick and is spent.',
    entreTesoros: (desde, hacia) =>
      `Moves from ${desde} to ${hacia}: the money doesn't leave, it just changes pockets.`,
    entreTesorosSinElegir:
      "Moves from one bucket to another: the money doesn't leave, it just changes pockets.",
    elHogarQueda: (saldo) => `The household will be at ${saldo}.`,
    elHogarQuedaEnNegativo: (saldo) => `The household will be at ${saldo}, in the red.`,
    elTallerQueda: (saldo) => `The shop will be at ${saldo}.`,
    elTallerQuedaEnNegativo: (saldo) => `The shop will be at ${saldo}, in the red.`,
    cocosQueda: (saldo) => `Cocos will be at ${saldo}.`,
    cocosQuedaEnNegativo: (saldo) => `Cocos will be at ${saldo}, in the red.`,
    cocosQuedaDeLaMeta: (saldo, meta) => `Cocos will be at ${saldo} of its ${meta} goal.`,
    teVanAQuedarPorPagar: (saldo) => `After this payment, you'll still owe ${saldo}.`,
    tePasas: (saldo) => `With this payment, you'll go over by ${saldo}.`,
    quedasAlDia: "With this payment, you'll be up to date.",
    compra: "Swaps pesos for dollars: the money doesn't leave, it just changes currency.",
    venta: "Swaps dollars for pesos: the money doesn't leave, it just changes currency.",
    quedan: (desde, quedaDesde, hacia, quedaHacia) =>
      `${desde} will be at ${quedaDesde}, and ${hacia} at ${quedaHacia}.`,
    quedanConElPrimeroEnNegativo: (desde, quedaDesde, hacia, quedaHacia) =>
      `${desde} will be at ${quedaDesde}, in the red, and ${hacia} at ${quedaHacia}.`,
    ingresoEnDolares:
      'Goes into the dollar bucket you pick, without going through the shop or the tithe.',
    entraA: (tesoro) => `Goes into ${tesoro}, without going through the shop or the tithe.`,
    queda: (tesoro, saldo) => `${tesoro} will be at ${saldo}.`,
    quedaEnNegativo: (tesoro, saldo) => `${tesoro} will be at ${saldo}, in the red.`,
  },
  diezmo: {
    debes: 'You owe',
    debesElImporte: (importe) => `You owe ${importe}`,
    deLoQueYaCobraste: "from what you've collected and haven't given yet",
    pagasteDeMas: 'You overpaid',
    pagasteElImporteDeMas: (importe) => `You overpaid by ${importe}`,
    seDescuenta: "it comes off the next tithe that's generated",
    estasAlDia: "You're up to date",
    todoPagado: 'everything generated is already paid',
  },
  resumenDelMes: {
    entroAlHogar: 'Household income',
    gastoElHogar: 'Household spending',
    facturoElTaller: 'Shop revenue',
  },
  libro: {
    motivoDelBloqueo: {
      'del-proyecto':
        "This entry comes from the job: it's built from its payments, its expenses and the split that was locked in when it was paid. To change it, correct the job.",
      ajuste:
        "An adjustment can't be edited: it's the record of a correction that was already made. If it's wrong, offset it with another adjustment in the opposite direction.",
    },
    etiquetaDerivada: {
      cobro: 'Job payment',
      gasto: 'Job expense',
      diezmo: 'Tithe from the split',
      sueldo: "Owner's pay from the split",
      fijos: 'Fixed costs from the split',
      prioridad: 'Split step',
      reparto: 'Share of the split',
    },
    delTrabajo: 'From the job',
    ajusteDeSaldo: 'Balance adjustment',
    movimiento: 'Transaction',
    otroTesoro: 'Another bucket',
    yaEstabaEnTusSaldos: 'already in your balances',
    sinConfirmar: 'unconfirmed',
    sinEfectoEnLosSaldos: 'no effect on balances',
    conElDolarA: (dolar) => `at ${dolar} per dollar`,
  },
  ficha: {
    fecha: 'Date',
    dolar: 'Dollar rate',
    saleDe: 'From',
    entraA: 'To',
    categoria: 'Category',
    deAfueraDelTaller: 'outside the shop',
    seVaDelTaller: 'out of the shop',
    yaEnLaApertura:
      "It's from before you started using the app: this money was already in your balances, so it's recorded with its date but doesn't move the buckets.",
    editar: 'Edit',
    borrar: 'Delete',
    verElTrabajo: (titulo) => `View “${titulo}”`,
    verElTrabajoSinTitulo: 'View the job',
  },
  casillaDeLaApertura: 'This money was already in your balances when you started using the app',
  cambioEnElLibro: (sale, entra, cotizacion) => `${sale} → ${entra} · at ${cotizacion}`,
  equivalenteDeLaCompra: (pesos, cotizacion, fecha) =>
    `≈ ${pesos} at ${cotizacion}, your last dollar purchase (${fecha})`,
  equivalenteDeLaVenta: (pesos, cotizacion, fecha) =>
    `≈ ${pesos} at ${cotizacion}, your last dollar sale (${fecha})`,
  comprarDolares: 'Buy dollars',
  venderDolares: 'Sell dollars',
} satisfies Mensajes['movimiento'];
