import type { Mensajes } from '../es';

import { plural } from './plural';

export const paginaProyectos = {
  comun: {
    proyectos: 'Jobs',
    volverAProyectos: 'Back to Jobs',
    noEsta: "That job isn't here",
    noEstaTexto:
      'You may have deleted it from another device, or the link points to a job from another shop.',
    mostrarleAlCliente: 'Show the client',
    editar: 'Edit',
    contactarA: (cliente) => `Contact ${cliente}`,
    darPorPerdido: 'Mark as lost',
    siNoSale: "If it doesn't happen",
    notas: 'Notes',
    notasEjemplo: 'What they told you on the phone, measurements, directions…',
    presupuesto: 'Quote',
    todaviaSinPresupuesto: 'No quote yet',
    senaCobrada: 'Deposit collected',
    sinSena: 'No deposit',
    telefono: 'Phone',
    sinTelefono: 'No phone',
    estabaEn: 'Previous stage',
    cobrado: 'Collected',
    saldo: 'Balance',
    sinSaldo: 'Paid in full',
    todos: 'All',
    buscarPorClienteOTrabajo: 'Search by client or job',
    limpiarLaBusqueda: 'Clear search',
    fechaYCuando: (fecha, cuando) => `${fecha}, ${cuando}`,
  },
  ficha: {
    fechas: {
      inicio: 'Start',
      listo: 'Ready',
      entregaEstimada: 'Estimated delivery',
      entregaComprometida: 'Confirmed delivery',
      entregado: 'Delivered',
      cerrado: 'Closed',
      cobrado: 'Paid',
    },
    recienAprobado: "Moved from Inquiries to Active, with what you'd already collected included.",
    cobrarElSaldo: (saldo) => `Collect the ${saldo} balance`,
    cobrarYRepartir: 'Collect and split',
    pagosRecibidos: 'Payments received',
    cuantosPagos: (pagos) => plural(pagos, { one: '# payment', other: '# payments' }),
    sinPagos: "You haven't collected anything for this job yet. The deposit usually comes first.",
    pago: 'Payment',
    gastosEInsumos: 'Expenses and supplies',
    cuantosGastos: (gastos) => plural(gastos, { one: '# item', other: '# items' }),
    sinGastos:
      "No expenses yet. Everything you buy for this piece goes here and is deducted from the job's income.",
    insumo: 'Supply',
    totalDeGastos: 'Total expenses',
    cargarPagosYGastos: 'Add payments and expenses',
    congelados: {
      cobrado: 'This job is paid: its payments and expenses were locked with the split.',
      perdido: 'This job is lost: its payments and expenses were locked with the split.',
    },
    entregaYComprobante: 'Delivery and invoice',
    direccionDeEntrega: 'Delivery address',
    sinDireccion: 'No address',
    otraDireccion: "Different from the client's address",
    abrirEnElMapa: 'Open on the map',
    comprobante: 'Invoice to issue',
    formaDePago: 'Payment method',
    sinDefinir: 'Not set',
    notasDeObra: 'Job notes',
    notasDeObraEjemplo: "Measurements, what's missing, what to discuss with the client…",
  },
  contacto: {
    consultas: 'Inquiries',
    sinFecha: 'No date',
    vencioEl: (fecha) => `Expired on ${fecha}`,
    datosDelContacto: 'Contact details',
    relevamiento: 'Site measure',
    visita: 'Site measure',
    cambiarElRelevamiento: 'Change the site measure date',
    cambiarLaVisita: 'Change the site measure date',
    cambiar: 'Change',
    valeHasta: 'Valid until',
    cambiarLaVigencia: 'Change how long the quote is valid',
    presupuestoAntesDel: 'Quote due by',
    sinFechaLimite: 'No deadline',
    gastosCargados: 'Expenses added',
    yaEntroALaCaja:
      "The deposit already went into the shop's cash and the expenses already came out: you'll see them in Finances from the day you added them.",
    cargarOtroPago: 'Add another payment or an expense',
    siNoSaleConSena: (sena) =>
      `If they said “not for now,” move them to Follow-up with the day you'll write to them again: they leave your Inquiries and the calendar reminds you. If it's a no, the ${sena} deposit is settled as shop income, and the contact moves to History. You can reactivate it.`,
    siNoSaleSinSena:
      "If they said “not for now,” move them to Follow-up with the day you'll write to them again: they leave your Inquiries and the calendar reminds you. If it's a no, it moves to History without moving any money. You can reactivate it.",
    porAhoraNo: 'Not for now',
  },
  seguimiento: {
    seguimiento: 'Follow-up',
    sinDia: 'No date to write to them again',
    hoy: 'Write to them again today',
    leTocaba: (fecha) => `Was due on ${fecha}`,
    leVolvesAEscribir: (fecha) => `Write to them again on ${fecha}`,
    proximoContacto: 'Next follow-up',
    registrarElContacto: 'Log the follow-up',
    cuandoLeEscribas:
      'When you write to them, log it: there you choose whether it goes back to Inquiries, stays in Follow-up with another date, or is a no.',
    datosDelTrabajo: 'Job details',
    historia: 'Follow-up history',
    sinHistoria: "You haven't written to them again since it moved to Follow-up.",
    siNoSaleConSena: (sena) =>
      `The ${sena} deposit is settled as shop income, and the job moves to History. You can reactivate it.`,
    siNoSaleSinSena: 'It moves to History without moving any money. You can reactivate it.',
  },
  lista: {
    metricas: {
      proyectos: 'jobs',
      enCurso: 'in progress',
      entregadosConSaldo: 'delivered with a balance due',
      cobrados: 'paid',
    },
    ordenarPor: 'Sort by',
    vacio: {
      activos: {
        titulo: 'No active jobs yet',
        detalle:
          'Here are the jobs clients approved. Contacts and quotes waiting for an answer live in Inquiries, and move to this tab on their own when you mark them approved.',
      },
      historial: {
        titulo: "You haven't closed any jobs yet",
        detalle:
          'When you collect the first one, the history of what you earned on each will show up here.',
      },
    },
    cargarUnProyecto: 'Add a job',
    cargarContacto: 'Add contact',
    nuevoProyecto: 'New job',
    etapa: 'Stage',
    buscarPorCliente: 'Search by client',
    ordenar: 'Sort',
    ningunoCoincide: (busqueda) => `No job matches “${busqueda}.”`,
    ningunoEnEseEstado: 'No jobs with that status.',
  },
  consultas: {
    visita: 'Site measure',
    vacioTitulo: 'No inquiries for now',
    vacioDetalle:
      "When someone calls you, add them here with what they want and the date of the site measure. If they left you a deposit at the site measure, add it: it goes into the shop's cash from that day. Once they approve it, it moves to Active.",
    cargarElPrimero: 'Add your first contact',
    buscarContacto: 'Search contacts',
    ningunoCoincide: (busqueda) => `No contact matches “${busqueda}.”`,
    ningunoEnEsaEtapa: 'No contacts at that stage.',
    orden: 'Longest waiting first; scheduled site measures last.',
    contactos: 'Contacts',
  },
  listaDeSeguimiento: {
    sinFecha: 'No date to write to them again',
    leTocaHoy: 'Due today',
    atrasado: (fecha, cuando) => `Overdue: was due ${fecha}, ${cuando}`,
    elDia: (fecha, cuando) => `${fecha}, ${cuando}`,
    volverAEscribirle: 'Write to them again',
    vacioTitulo: 'No one in Follow-up',
    vacioDetalle:
      "When an inquiry tells you “not for now,” move it to Follow-up from its page with the day you'll write to them again. They're listed here in order, overdue first, and the calendar reminds you when it's time.",
    buscarEnSeguimiento: 'Search Follow-up',
    nadieCoincide: (busqueda) => `No one in Follow-up matches “${busqueda}.”`,
    orden: "By the day you'll write to them again: overdue first.",
    enSeguimiento: 'In follow-up',
  },
  insumos: {
    insumosDelTrabajo: 'Job supplies',
    insumos: 'Supplies',
    enMaun: "in Maun until it's paid",
    entro: 'Came in',
    gastado: 'Spent',
    queda: 'Left',
    nada: 'Nothing',
  },
  analitico: 'Delivery insights',
  presupuesto: {
    volverAlTrabajo: 'Back to the job',
    yaNoSeCambia: "This quote can't be changed anymore",
    yaNoSeCambiaTexto:
      'The job is already approved or closed. What you sent stays on its page, with its PDF.',
  },
  vistaCliente: {
    volverAlTrabajo: 'Back to the job',
    volverA: (trabajo) => `Back to “${trabajo}”`,
    sinSenal: "You're offline: this is the last version we loaded. It may be out of date.",
    noEsta: "That job isn't here",
    noEstaTexto: 'You may have deleted it, or the link points to a job from another shop.',
  },
} satisfies Mensajes['paginaProyectos'];
