import type { Mensajes } from '../es';

import { plural } from './plural';

export const proyecto = {
  estados: {
    contacto: 'Contact',
    presupuesto_estimativo: 'Estimate sent',
    relevamiento: 'Site measure',
    a_presupuestar: 'To quote',
    presupuesto_enviado: 'Quote sent',
    en_seguimiento: 'In follow-up',
    perdido: 'Lost',
    en_curso: 'In progress',
    entregado: 'Delivered',
    cobrado: 'Paid',
  },
  formasDePago: {
    efectivo: 'Cash',
    transferencia: 'Bank transfer',
    cuotas: 'Installments',
    mixto: 'Mixed',
  },
  comprobantes: {
    factura_a: 'Invoice A',
    factura_b: 'Invoice B',
    factura_c: 'Invoice C',
    remito: 'Delivery note',
    sin_comprobante: 'No invoice',
  },
  etapas: {
    consultas: 'Inquiries',
    seguimiento: 'Follow-up',
    activos: 'Active',
    historial: 'History',
  },
  orden: {
    cliente: 'Client',
    trabajo: 'Job',
    presupuesto: 'Quote',
    cobrado: 'Collected',
    saldo: 'Balance',
    entrega: 'Delivery',
    estado: 'Status',
  },
  cambios: {
    volverAContacto: 'Back to contact',
    mandeUnEstimativo: 'Mark estimate as sent',
    pasarARelevamiento: 'Move to site measure',
    pasarAPresupuestar: 'Start quoting',
    mandeElPresupuesto: 'Mark quote as sent',
    volvioAPresupuesto: 'Back to quote',
    yaLoAprobo: 'Mark as approved',
    volvioAlTaller: 'Back in the shop',
    porAhoraNo: 'Not for now',
    yaLoEntregue: 'Mark as delivered',
  },
  cobro: {
    instancias: {
      sena: 'Deposit',
      saldo: 'Balance',
    },
    formas: {
      transferencia: 'Bank transfer',
      efectivo: 'Cash',
    },
  },
  consultas: {
    irARelevarEl: (fecha) => `Do the site measure on ${fecha}`,
    visitaDentroDe: (cuando) => `Site measure ${cuando}`,
    irARelevarHoy: 'Do the site measure today',
    laVisitaEsHoy: 'The site measure is today',
    estimativoEnviadoHoy: 'Estimate sent today',
    estimativoSinRespuesta: (cuando) => `Estimate sent ${cuando}, no reply yet`,
    siAvanzaFaltaAgendar: 'If it goes ahead, schedule the site measure',
    yaPagoLaVisita: 'The site measure is paid: time to quote',
    faltaQueApruebeElEstimativo:
      'Waiting for the client to approve the estimate and pay for the site measure',
    faltaPonerleFecha: 'Set a date for the site measure',
    relevamientoSinFecha: (cuando) => `Last contact ${cuando}, no site measure date`,
    faltaPasarLoRelevado: 'Mark the site measure as done to start quoting',
    laVisitaFue: (cuando) => `The site measure was ${cuando}`,
    aPresupuestarDesde: (cuando) => `Quote pending, last contact ${cuando}`,
    yaEstaArmado: "It's ready: send the quote",
    faltaPresupuestarConTareas: (hechas, total) =>
      `Quote pending: ${String(hechas)} of ${String(total)} tasks done`,
    faltaPresupuestar: 'Make the quote',
    faltaElEstimativo: "Send an estimate: the site measure isn't paid",
    vencioElPresupuesto: 'The quote expired: update it or change its date',
    valiaHasta: (fecha) => `Was valid until ${fecha}`,
    faltaLlamar: 'Call to find out',
    presupuestoEnviadoHoy: 'Quote sent today',
    presupuestoSinRespuesta: (cuando) => `Quote sent ${cuando}, no reply yet`,
    faltaAgendarLaVisita: 'Schedule the site measure',
    contactoSinVisita: (cuando) => `Last contact ${cuando}, no site measure scheduled`,
    pasos: {
      yaLoAprobo: 'Mark as approved',
      yaFuiARelevar: 'Mark site measure as done',
      mandeElPresupuesto: 'Mark quote as sent',
      agendarLaVisita: 'Schedule site measure',
      mandeUnEstimativo: 'Mark estimate as sent',
      mandeElEstimativo: 'Mark estimate as sent',
      pasarAPresupuestar: 'Start quoting',
      loAproboPasarAProyectos: 'Approved: move to Jobs',
      seguirArmandolo: 'Keep building the quote',
      armarElPresupuesto: 'Build the quote',
    },
  },
  corte: {
    sinCorte: (mes) =>
      `${mes} hasn't been split yet. When you close a job, you'll see here where each peso goes.`,
    sinNadaCobrado: (trabajos, mes) =>
      `${plural(trabajos, { one: 'One job closed', other: '# jobs closed' })} in ${mes}, with nothing collected: there was nothing to split.`,
    sinIngreso: (trabajos, mes) =>
      `${plural(trabajos, { one: 'One job closed', other: '# jobs closed' })} in ${mes}, and expenses ate up what was collected: there was no income left to split.`,
    repartido: (trabajos, mes, partes) =>
      `${plural(trabajos, { one: 'One job closed', other: '# jobs closed' })} in ${mes}: ${partes}.`,
    repartidoConGastos: (trabajos, mes, partes) =>
      `${plural(trabajos, { one: 'One job closed', other: '# jobs closed' })} in ${mes}: ${partes}. The rest went to expenses.`,
    alHogar: (parte) => `${parte} to the household`,
    alTaller: (parte) => `${parte} to the shop`,
    alDiezmo: (parte) => `${parte} to the tithe`,
    aOtroTesoro: (parte, tesoro) => `${parte} to ${tesoro}`,
    menosDelUno: 'less than 1%',
    gastos: 'Expenses',
  },
  tesoroSinNombre: 'Bucket',
  costos: {
    madera: 'Wood',
    herrajes: 'Hardware',
    flete: 'Freight',
    ayudante: 'Helper',
  },
  despiece: {
    clases: {
      sueldo: "Owner's pay",
      fijos: 'Fixed costs',
      prioridad: 'Fixed savings',
    },
    topeDelMes: 'Monthly cap',
    diezmo: (porcentaje) => `Tithe ${porcentaje}%`,
    diezmoSobreLoCobrado: (porcentaje) => `Tithe ${porcentaje}% of what you collect`,
    diezmoSobreElIngreso: (porcentaje) => `Tithe ${porcentaje}% of income`,
    obligacion: (tesoro, porcentaje) => `${tesoro} ${porcentaje}%`,
    obligacionSobreLoCobrado: (tesoro, porcentaje) =>
      `${tesoro} ${porcentaje}% of what you collect`,
    obligacionSobreElIngreso: (tesoro, porcentaje) => `${tesoro} ${porcentaje}% of income`,
    deLoQueSobra: (porcentaje) => `${porcentaje}% of what's left`,
    elResto: 'The rest',
  },
  distribucion: {
    titulo: 'Income split',
    grupos: {
      obligacion: 'Obligations',
      compromiso: 'Bills',
      ahorro: 'Savings',
      superavit: 'Surplus',
    },
    resto: 'Rest',
    aTesoro: (tesoro) => `to ${tesoro}`,
    detalle: (etiqueta, monto) => `${etiqueta}: ${monto}`,
    detalleATesoro: (etiqueta, tesoro, monto) => `${etiqueta} to ${tesoro}: ${monto}`,
    faltan: (monto) => `${monto} to go`,
    cubierto: 'already covered by other payments this month',
    conSuSaldo: 'already has its amount',
    llegaALaMeta: 'reached its goal',
    cobradosMenosGastos: (cobrado, gastos) => `${cobrado} collected minus ${gastos} in expenses`,
    ingreso: 'Income',
    sinCobrar:
      "No money has come in for this job yet. Once it's paid, you'll see here how the income flows down the waterfall of buckets.",
    sinIngreso:
      "Expenses ate up what was collected: there's no income to split, and the loss stays in the shop's cash.",
    proyeccion:
      "Projection based on what's been collected so far, using the waterfall. The split becomes final once the job is paid.",
    provisoria:
      "The server hasn't confirmed this split yet: it's the one that will stay if nothing changed on the other side. It confirms itself when you're back online.",
  },
  entrega: {
    franjas: {
      manana: 'in the morning',
      tarde: 'in the afternoon',
    },
    conFranja: {
      manana: (dia) => `${dia}, in the morning`,
      tarde: (dia) => `${dia}, in the afternoon`,
    },
    vencida: (cuando) => `was due ${cuando}`,
    venceHoy: 'due today',
    venceManana: 'due tomorrow',
    enDias: (dias) => plural(dias, { one: 'in # day', other: 'in # days' }),
    comprometida: 'confirmed',
    sinFecha: 'No date',
    conFranjaComprometida: (fecha) => `${fecha} · confirmed`,
  },
  formulario: {
    sinMonto: 'Enter the amount, in pesos.',
    demasiadoLargo: (maximo) =>
      plural(maximo, {
        one: "Can't be longer than # character.",
        other: "Can't be longer than # characters.",
      }),
    sinFecha: 'Enter the date.',
    sinCliente: 'Choose a client, or create a new one from here.',
    sinTitulo: 'Say what piece of furniture it is.',
    presupuestoNegativo: "Check the quote: it's in pesos.",
    senaFueraDeRango: 'The deposit must be between 0 and 100.',
  },
  insumos: {
    tallerPuso: (monto) => `The shop put in ${monto}.`,
    enOtroTesoro: (monto, tesoro) => `Another ${monto} from this job is in “${tesoro}”.`,
  },
  plata: {
    conSuValorEnPesos: (loQueSePago, enPesos) => `${loQueSePago} (${enPesos})`,
  },
  pago: {
    descuenta: (monto) => `Covers ${monto} of the price.`,
    vale: (monto) => `Counts as ${monto} for the split.`,
    descontoConElDolar: (monto, dolar) => `Covered ${monto} of the price, at ${dolar} per dollar.`,
    valioConElDolar: (monto, dolar) => `Counted as ${monto} for the split, at ${dolar} per dollar.`,
  },
  liquidacion: {
    operaciones: {
      cobro: 'Payment',
      cierre: 'Closing as lost',
      reapertura: 'Reopening the payment',
      reactivacion: 'Reactivating the quote',
    },
    elRepartoSalioDistinto: 'The split came out different from what you saw.',
    diferencia: (tesoro, esperado, quedo) =>
      `${tesoro}: you expected ${esperado} and it ended up at ${quedo}.`,
    diferenciaPorLoQueTenia: (tesoro, esperado, quedo, tenia) =>
      `${tesoro}: you expected ${esperado} and it ended up at ${quedo}, because it already had ${tenia}.`,
    diferenciaPorElMes: (tesoro, esperado, quedo, llevaba) =>
      `${tesoro}: you expected ${esperado} and it ended up at ${quedo}, because the month already had ${llevaba} from another job.`,
    quedoEnElTaller: (quedo, esperado) =>
      `The difference stayed with the shop: ${quedo} instead of ${esperado}.`,
    quedoEnElRemanente: (quedo, esperado) =>
      `The difference stayed in the shop's share: ${quedo} instead of ${esperado}.`,
    escalones: {
      sueldo: "Owner's pay",
      fijos: 'Fixed costs',
    },
  },
  marca: {
    enPausa: {
      cobro: 'Paid, not confirmed',
      cierre: 'Closed, not confirmed',
      reapertura: 'Reopened, not confirmed',
      reactivacion: 'Reactivated, not confirmed',
    },
    confirmando: {
      cobro: 'Confirming the payment…',
      cierre: 'Confirming the closing…',
      reapertura: 'Confirming the reopening…',
      reactivacion: 'Confirming the reactivation…',
    },
    rechazado: 'The server rejected it',
  },
  listo: 'Ready',
  necesidades: {
    material: {
      titulo: 'Materials needed',
      agregar: 'Add material',
      campo: 'What material is needed',
      cuantos: 'Material quantity',
      placeholder: 'Melamine boards, plank, lacquer…',
      ayuda: 'What you need to buy or order: cuts, planks, paint. Put the size in the name.',
      casilla: (necesidad) => `Ready: ${necesidad}`,
      cuantosListos: (listos, total) => `${String(listos)} of ${String(total)} ready`,
    },
    herraje: {
      titulo: 'Hardware needed',
      agregar: 'Add hardware',
      campo: 'What hardware is needed',
      cuantos: 'Hardware quantity',
      placeholder: 'Hinges, gas struts, pulls…',
      ayuda: 'What you need to order for this job. Quantity is optional.',
      casilla: (necesidad) => `Ready: ${necesidad}`,
      cuantosListos: (listos, total) => `${String(listos)} of ${String(total)} ready`,
    },
    herramienta: {
      titulo: 'Tools needed',
      agregar: 'Add tool',
      campo: 'What tool is needed',
      cuantos: 'Tool quantity',
      placeholder: 'Circular saw, belt sander…',
      ayuda: 'What you need to have on hand the day you do it. Quantity is optional.',
      casilla: (necesidad) => `Ready: ${necesidad}`,
      cuantosListos: (listos, total) => `${String(listos)} of ${String(total)} ready`,
    },
  },
  obra: {
    faltaEntregarlo: 'Still to deliver',
    entregaComprometida: (fecha, cuando) => `Confirmed delivery: ${fecha} (${cuando})`,
    faltaAcordarLaEntrega: 'Agree on a delivery date',
    listoDesde: (fecha) => `Ready since ${fecha}`,
    sinEntregaEstimada: 'No estimated delivery date',
    entregaEstimada: (cuando) => `Estimated delivery: ${cuando}`,
    faltaCobrar: (saldo) => `Still to collect: ${saldo}`,
    faltaCobrarloYRepartir: 'Collect the payment and split it',
    entregadoSinFecha: 'Delivered, no delivery date',
    entregadoEl: (fecha) => `Delivered on ${fecha}`,
  },
  clienteBorrado: 'Deleted client',
  resultadosDelContacto: {
    reactivado: 'Back to Inquiries',
    perdido: 'Marked as lost',
    otra_fecha: 'Stayed in Follow-up with a new date',
  },
  tareas: {
    etiquetas: {
      presupuesto_diseno: 'Design',
      presupuesto_despiece: 'Make the cut list',
      presupuesto_cotizacion: 'Price the materials',
      presupuesto_pdf: 'Build the quote',
    },
    detalleDeCotizar: 'Wood and hardware, freight, helper',
  },
  tiposDeArranque: {
    cocina: 'Kitchen',
    placard: 'Wardrobe',
    vestidor: 'Walk-in closet',
    vanitory: 'Vanity',
    muebleDeTv: 'TV unit',
    biblioteca: 'Bookcase',
    escritorio: 'Desk',
  },
  sena: {
    titulo: 'Deposit to confirm',
    sinPresupuesto:
      "There's no quote yet, so there's no deposit to calculate. Add it, or check the option the client approved.",
    delTrabajo: (porcentaje) => `${porcentaje}% of the quote, set for this job`,
    delTaller: (porcentaje) => `${porcentaje}% of the quote, the shop's default`,
    sena: 'Deposit',
    cobrado: 'Collected',
    falta: 'Still due',
    nada: 'Nothing',
    cubiertaDeMas: (deMas) => `The deposit is covered, and you collected ${deMas} extra.`,
    cubierta: 'The deposit is covered.',
  },
  costosDeCotizar: {
    titulo: 'Estimated costs',
    ayuda:
      "What you figure you'll spend. It doesn't touch the quote: you set that yourself, with the income you want it to leave you.",
    cargadas: (cargadas, total) => `${String(cargadas)} of ${String(total)}`,
    sinEstimar: 'Not estimated',
    costoEstimado: 'Estimated cost',
    sinPresupuesto: 'Once the job has a quote, what you keep shows up here.',
    presupuesto: 'Quote',
    teQuedaSiTeLoAprueban: 'You keep, if approved',
    teQueda: 'You keep',
    enContra: "You're estimating more costs than the quote.",
  },
  liquidacionesSinConfirmar: {
    unProyecto: 'A job',
    cuentan: (liquidaciones) =>
      plural(liquidaciones, {
        one: "These balances include a settlement the server hasn't confirmed yet:",
        other: "These balances include # settlements the server hasn't confirmed yet:",
      }),
  },
} satisfies Mensajes['proyecto'];
