import {
  Archive,
  ArrowDown,
  ArrowLeftRight,
  ArrowRight,
  ArrowUp,
  ArrowUpDown,
  ArrowUpRight,
  Banknote,
  Bell,
  BellOff,
  Building2,
  Calendar,
  CalendarCheck,
  CalendarDays,
  Car,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  Church,
  Circle,
  CircleAlert,
  CircleCheck,
  CircleDot,
  CircleHelp,
  Clock,
  CloudOff,
  Coins,
  Copy,
  Download,
  Eye,
  EyeOff,
  FaceAngry,
  FaceGrinning,
  FaceNeutral,
  FaceSlightlyFrowning,
  FaceSlightlySmiling,
  FileText,
  FingerprintPattern,
  FolderKanban,
  FolderPlus,
  Gem,
  Gift,
  GraduationCap,
  GripVertical,
  Hammer,
  HandCoins,
  Heart,
  House,
  Image as ImagenLucide,
  Info,
  Landmark,
  Link2,
  Link2Off,
  ListChecks,
  LoaderCircle,
  Lock,
  LogOut,
  Mail,
  MapPin,
  Maximize2,
  MessageCircle,
  MessageSquarePlus,
  MessageSquareQuote,
  Minus,
  MonitorSmartphone,
  Moon,
  Package,
  Pencil,
  PencilLine,
  PencilRuler,
  Percent,
  Phone,
  PiggyBank,
  Plane,
  Plus,
  QrCode,
  Receipt,
  Redo2,
  RefreshCw,
  RotateCcw,
  RotateCcwClock,
  Route,
  Ruler,
  Scan,
  Search,
  Send,
  Settings,
  Share2,
  Shield,
  Smartphone,
  Split,
  Sprout,
  Star,
  Sun,
  Table,
  ThumbsDown,
  ThumbsUp,
  Trash2,
  TrendingUp,
  TriangleAlert,
  Truck,
  Undo2,
  UserPlus,
  Users,
  Vault,
  Wallet,
  Wrench,
  X,
} from 'lucide-react';

const ICONOS = {
  angry: FaceAngry,
  archive: Archive,
  'arrow-down': ArrowDown,
  'arrow-left-right': ArrowLeftRight,
  'arrow-right': ArrowRight,
  'arrow-up': ArrowUp,
  'arrow-up-down': ArrowUpDown,
  'arrow-up-right': ArrowUpRight,
  banknote: Banknote,
  bell: Bell,
  'bell-off': BellOff,
  'building-2': Building2,
  calendar: Calendar,
  'calendar-check': CalendarCheck,
  'calendar-days': CalendarDays,
  car: Car,
  check: Check,
  'chevron-down': ChevronDown,
  'chevron-left': ChevronLeft,
  'chevron-right': ChevronRight,
  'chevron-up': ChevronUp,
  church: Church,
  circle: Circle,
  'circle-alert': CircleAlert,
  'circle-check': CircleCheck,
  'circle-dot': CircleDot,
  'circle-help': CircleHelp,
  clock: Clock,
  'cloud-off': CloudOff,
  coins: Coins,
  copy: Copy,
  download: Download,
  eye: Eye,
  'eye-off': EyeOff,
  'file-text': FileText,
  fingerprint: FingerprintPattern,
  'folder-kanban': FolderKanban,
  'folder-plus': FolderPlus,
  gem: Gem,
  frown: FaceSlightlyFrowning,
  gift: Gift,
  'graduation-cap': GraduationCap,
  'grip-vertical': GripVertical,
  hammer: Hammer,
  'hand-coins': HandCoins,
  heart: Heart,
  history: RotateCcwClock,
  house: House,
  image: ImagenLucide,
  info: Info,
  landmark: Landmark,
  laugh: FaceGrinning,
  'link-2': Link2,
  'link-2-off': Link2Off,
  'list-checks': ListChecks,
  'loader-circle': LoaderCircle,
  lock: Lock,
  'log-out': LogOut,
  mail: Mail,
  'map-pin': MapPin,
  'maximize-2': Maximize2,
  meh: FaceNeutral,
  'message-circle': MessageCircle,
  'message-square-plus': MessageSquarePlus,
  'message-square-quote': MessageSquareQuote,
  minus: Minus,
  'monitor-smartphone': MonitorSmartphone,
  moon: Moon,
  package: Package,
  pencil: Pencil,
  'pencil-line': PencilLine,
  'pencil-ruler': PencilRuler,
  percent: Percent,
  phone: Phone,
  'piggy-bank': PiggyBank,
  plane: Plane,
  plus: Plus,
  'qr-code': QrCode,
  receipt: Receipt,
  'redo-2': Redo2,
  'refresh-cw': RefreshCw,
  'rotate-ccw': RotateCcw,
  route: Route,
  ruler: Ruler,
  scan: Scan,
  search: Search,
  send: Send,
  settings: Settings,
  'share-2': Share2,
  shield: Shield,
  smartphone: Smartphone,
  smile: FaceSlightlySmiling,
  split: Split,
  sprout: Sprout,
  star: Star,
  sun: Sun,
  table: Table,
  'thumbs-down': ThumbsDown,
  'thumbs-up': ThumbsUp,
  'trash-2': Trash2,
  'trending-up': TrendingUp,
  'triangle-alert': TriangleAlert,
  truck: Truck,
  'undo-2': Undo2,
  'user-plus': UserPlus,
  users: Users,
  vault: Vault,
  wallet: Wallet,
  wrench: Wrench,
  x: X,
} as const;

export type NombreDeIcono = keyof typeof ICONOS;

export interface IconoProps {
  nombre: NombreDeIcono;
  tamano?: number;
  grosor?: number;
  className?: string;
}

export function Icono({ nombre, tamano = 20, grosor = 1.75, className }: IconoProps) {
  const Dibujo = ICONOS[nombre];
  return (
    <Dibujo
      aria-hidden
      focusable={false}
      size={tamano}
      strokeWidth={grosor}
      className={className}
    />
  );
}
