export const appNavegacion = {
  pantallas: {
    inicio: 'Inicio',
    agenda: 'Agenda',
    consultas: 'Consultas',
    seguimiento: 'Seguimiento',
    proyectos: 'Proyectos',
    historial: 'Historial',
    proyectoNuevo: 'Proyecto nuevo',
    analitico: 'Analítico de entregas',
    editarProyecto: 'Editar proyecto',
    presupuesto: 'El presupuesto',
    aprobar: 'Aprobar',
    mostrarleAlCliente: 'Mostrarle al cliente',
    loQueVeElCliente: 'Lo que ve el cliente',
    cobrar: 'Cobrar',
    darPorPerdido: 'Dar por perdido',
    clientes: 'Clientes',
    finanzas: 'Finanzas',
    tesoros: 'Tesoros',
    opiniones: 'Opiniones',
    diezmo: 'Diezmo',
    estadisticas: 'Estadísticas',
    ajustes: 'Ajustes',
    avisos: 'Avisos',
    tuPresupuesto: 'Tu presupuesto',
  },
} as const;
