export const editarCliente = {
  editar: 'Editar cliente',
  nuevo: 'Cliente nuevo',
  nombre: 'Nombre',
  comoLoTenesAgendado: 'Como lo tenés agendado',
  telefono: 'Teléfono',
  zona: 'Zona',
  localidadOBarrio: 'Localidad o barrio',
  email: 'Email',
  opcional: 'Opcional',
  direccion: 'Dirección',
  calleYNumero: 'Calle y número, localidad',
  comoLlego: 'Cómo llegó',
  sinEspecificar: 'Sin especificar',
  quienLoRefirio: 'Quién lo refirió',
  detalle: 'Detalle',
  nombreDeQuienLoRecomendo: 'Nombre de quien lo recomendó',
  loQueQuierasAnotar: 'Lo que quieras anotar',
  condicionFrenteAlIva: 'Condición frente al IVA',
  condicionYComprobante: (condicion: string, comprobante: string): string =>
    `${condicion}. Emite ${comprobante}.`,
  razonSocial: 'Razón social',
  siFacturaAUnaEmpresa: 'Si factura a una empresa',
  domicilioFiscal: 'Domicilio fiscal',
  siEsDistinto: 'Si es distinto de la dirección',
  notas: 'Notas',
  loQueConvengaRecordar: 'Lo que convenga recordar de este cliente',
  cancelar: 'Cancelar',
  guardarLosCambios: 'Guardar los cambios',
  guardarCliente: 'Guardar cliente',
} as const;
