export const editarProyecto = {
  pantalla: {
    cancelar: 'Cancelar',
    proyectoNuevo: 'Proyecto nuevo',
    editarProyecto: 'Editar proyecto',
    trabajo: 'Trabajo',
    trabajoEjemplo: 'Placard 3 puertas, mesada de cocina…',
    tipo: 'Tipo de proyecto',
    tipoEjemplo: 'Cocina, placard, vestidor…',
    tipoAyuda:
      'Con el tipo, el Analítico de entregas te muestra cuánto tardás en cada clase de mueble.',
    presupuesto: 'Presupuesto',
    sinDefinir: 'Sin definir',
    presupuestoDeLaOpcion:
      'Sale de la opción que tildes, abajo. Para escribirlo a mano, sacá las opciones.',
    presupuestoVacio: 'Dejalo vacío mientras no esté presupuestado.',
    senaPropia: 'Seña propia (%)',
    senaDelTaller: 'La del taller',
    senaAyuda:
      'Dejalo vacío para pedir la seña de siempre. Completalo solo si a este le pedís otra.',
    formaDePago: 'Forma de pago',
    fechaDeInicio: 'Fecha de inicio',
    entregaEstimada: 'Entrega estimada',
    entregaCalculada: 'Calculada a 21 días hábiles del inicio.',
    horaDeLaEntrega: 'Hora de la entrega',
    horaAyuda: 'Opcional. Con hora, la entrega cae en su renglón del día en la agenda.',
    estado: 'Estado',
    estadoCongelado: {
      cobrado:
        'Un proyecto cobrado tiene la distribución congelada: su estado se cambia reabriéndolo.',
      perdido:
        'Un proyecto perdido tiene la distribución congelada: su estado se cambia reabriéndolo.',
    },
    direccionDeEntrega: 'Dirección de entrega',
    usarLaDelCliente: 'Usar la del cliente',
    direccionEjemplo: 'Calle y número, localidad',
    abrirLaDireccion: 'Abrir la dirección en el mapa',
    comprobante: 'Comprobante a emitir',
    porLaCondicion: (condicion: string) => `Por ${condicion.toLowerCase()}`,
    notasDeObra: 'Notas de obra',
    notasEjemplo: 'Medidas, qué falta, qué hablar con el cliente…',
    repartoCerrado: {
      cobrado:
        'Este proyecto está cobrado y su reparto quedó cerrado: sus pagos y sus gastos no se tocan.',
      perdido:
        'Este proyecto está perdido y su reparto quedó cerrado: sus pagos y sus gastos no se tocan.',
    },
    reactivarlo: 'Reactivarlo para poder cargarlo',
    reabrirElCobro: 'Reabrir el cobro para corregirlo',
    alGuardarLoCierra:
      'Los campos se desbloquean acá mismo. Al guardar te llevo a cerrarlo de nuevo, con la seña repartida contando lo que cargaste.',
    alGuardarLoCobra:
      'Los campos se desbloquean acá mismo. Al guardar te llevo a cobrarlo de nuevo, con el reparto rehecho.',
    totales: {
      presupuesto: 'Presupuesto',
      cobrado: 'Cobrado',
      saldo: 'Saldo',
      neta: 'Neta',
    },
    guardarProyecto: 'Guardar proyecto',
    guardarLosCambios: 'Guardar los cambios',
  },
  filas: {
    pagos: {
      titulo: 'Pagos recibidos',
      detalle: (fila: number) => `Concepto ${String(fila)}`,
      quitar: (fila: number) => `Quitar concepto ${String(fila)}`,
      placeholder: 'Seña, adelanto, saldo…',
      agregar: 'Agregar un pago',
      ayuda: 'Lo que te pagó el cliente por este trabajo. Entra a la caja del taller.',
      vacio: 'Todavía no cobraste nada de este trabajo. La seña suele ir primero.',
    },
    gastos: {
      titulo: 'Gastos e insumos',
      detalle: (fila: number) => `Descripción ${String(fila)}`,
      quitar: (fila: number) => `Quitar descripción ${String(fila)}`,
      placeholder: 'Melamina, herrajes, flete…',
      agregar: 'Agregar un gasto',
      ayuda: 'Materiales y compras de este mueble. Se descuentan del ingreso del trabajo.',
      vacio: 'Todavía no cargaste gastos para este mueble.',
    },
    fecha: (fila: number) => `Fecha ${String(fila)}`,
    monto: (fila: number) => `Monto ${String(fila)}`,
    quiteLaFila: 'Quité la fila.',
    quite: (quitado: string) => `Quité ${quitado}.`,
    deshacer: 'Deshacer',
  },
  opciones: {
    titulo: 'Opciones que le presentaste',
    aprobada: (monto: string) => `Aprobada: ${monto}`,
    ayuda:
      'Los presupuestos que le presentaste. Tildá el que te aprobó y ese pasa a ser el presupuesto del trabajo.',
    agregar: 'Agregar una opción',
    sinOpciones: 'Sin opciones. Si le pasás un solo precio, cargalo arriba en Presupuesto.',
    queIncluye: (opcion: number) => `Qué incluye la opción ${String(opcion)}`,
    queIncluyeEjemplo: 'Solo el escritorio, los 2 escritorios…',
    estaAprobada: 'Aprobada',
    laAprobo: 'La aprobó',
    importe: (opcion: number) => `Importe de la opción ${String(opcion)}`,
    quitar: (opcion: number) => `Quitar la opción ${String(opcion)}`,
    quiteLaOpcion: 'Quité la opción.',
    quite: (quitado: string) => `Quité ${quitado}.`,
    deshacer: 'Deshacer',
  },
  opcionesDelTrabajo: {
    titulo: 'Opciones de presupuesto',
    cargarLaPrimera:
      'Si le presentás más de una variante, cargá cada una con su importe. Cuando elija, tildás la que aprobó.',
    cargarLasOpciones: 'Cargar las opciones',
    aprobaste: (monto: string) => `Aprobaste ${monto}: es el presupuesto del trabajo.`,
    sacasteLaAprobacion: 'Sacaste la aprobación: el trabajo queda sin presupuesto.',
    deshacer: 'Deshacer',
    cuantas: (opciones: number) => (opciones === 1 ? '1 opción' : `${String(opciones)} opciones`),
    sinAprobar: 'Tildá la que te aprobaron y ese importe pasa a ser el presupuesto del trabajo.',
    conAprobada: 'Las que no eligió quedan acá, para saber qué le ofreciste.',
    sinDetalle: 'Opción sin detalle',
    esElPresupuesto: 'Aprobada: es el presupuesto del trabajo',
    estaAprobada: 'Aprobada',
    laAprobo: 'La aprobó',
  },
  borrado: {
    borrar: 'Borrar',
    pregunta: (trabajo: string) => `¿Borrás «${trabajo}»?`,
    sinPlataDelContacto: 'No tiene seña ni gastos cargados, así que no se mueve plata.',
    sinPlataDelProyecto: 'No tiene pagos ni gastos cargados, así que no se mueve plata.',
    conPlata: (pagos: number, gastos: number) =>
      `Se va a llevar sus ${String(pagos)} pagos y sus ${String(gastos)} gastos, y con eso salen del libro mayor.`,
    cancelar: 'Cancelar',
    borrarElContacto: 'Borrar el contacto',
    borrarElProyecto: 'Borrar el proyecto',
  },
  avance: {
    titulo: 'Qué falta',
    yaEstaListo: 'Ya está listo',
    todaviaNoEstaListo: 'Todavía no está listo',
  },
  loQueHaceFalta: {
    titulo: 'Lo que hace falta',
    ayuda:
      'Los materiales y los herrajes que hay que pedir, y las herramientas que hay que tener el día que lo hagas. Se te sugieren los que ya usaste.',
    todoListo: 'todo listo',
    listas: (listas: number, cuantas: number) => `${String(listas)} de ${String(cuantas)}`,
    cosas: (cosas: number) => (cosas === 1 ? '1 cosa' : `${String(cosas)} cosas`),
    cerrado: 'Este trabajo está cerrado: la lista queda como quedó.',
    saque: (necesidad: string) => `Saqué ${necesidad} de la lista.`,
    deshacer: 'Deshacer',
    loQueMasUsas: 'Lo que más usás',
    yaLoUsasteAntes: 'Ya lo usaste antes',
    trabajos: (trabajos: number) => (trabajos === 1 ? '1 trabajo' : `${String(trabajos)} trabajos`),
    cantidadDe: (necesidad: string) => `Cantidad de ${necesidad}`,
    nombreDe: (necesidad: string) => `Nombre de ${necesidad}`,
    sacarDeLaLista: (necesidad: string) => `Sacar ${necesidad} de la lista`,
  },
} as const;
