export const editarTesoro = {
  moneda: {
    pregunta: '¿En qué moneda?',
    pesos: 'Pesos',
    dolares: 'Dólares',
    nota: 'La moneda no se cambia después. Un tesoro en dólares va al estante: la fila reparte pesos.',
    enPesos: 'En pesos',
    enDolares: 'En dólares',
  },
  archivar: {
    conDolaresSinDestino: 'Para archivarlo, vendé los dólares o pasalos a otro tesoro en dólares.',
    debeDolaresSinOrigen:
      'Para archivarlo, comprá los dólares que le faltan o traelos de otro tesoro en dólares.',
    queHacer:
      'Sacalo de la fila, cobrá el trabajo reabierto que lo usa y pasá su plata a otro tesoro. Después archivalo.',
    deSiempre: (nombre: string) => `${nombre} es uno de los tesoros de siempre: no se archiva.`,
    enLaFila: (nombre: string) => `${nombre} está en la fila: cada cobro le pasa plata.`,
    enUnCobroReabierto: (nombre: string, trabajo: string) =>
      `${nombre} está en el reparto de «${trabajo}», que reabriste: al volver a cobrarlo le pasa plata.`,
    loQueTenia: (nombre: string) => `Lo que tenía ${nombre} al archivarlo`,
    loQueLeFaltaba: (nombre: string) => `Lo que le faltaba a ${nombre} para archivarlo`,
    titulo: (nombre: string) => `Archivar ${nombre}`,
    tiene: (saldo: string) => `Tiene ${saldo}`,
    todaviaNo: (nombre: string) => `Todavía no se puede archivar ${nombre}.`,
    sinPlata: (nombre: string) =>
      `${nombre} deja de recibir plata y sigue apareciendo con su nombre en los repartos que ya hiciste.`,
    conPlata: (nombre: string) =>
      `Antes de archivarlo, ¿a dónde pasamos lo que tiene? ${nombre} deja de recibir plata y sigue apareciendo con su nombre en los repartos que ya hiciste.`,
    debe: (monto: string, nombre: string) =>
      `Antes de archivarlo hay que dejarlo en cero: le faltan ${monto}. ¿De qué tesoro sale? ${nombre} deja de recibir plata y sigue apareciendo con su nombre en los repartos que ya hiciste.`,
    aDondePasa: 'A dónde pasa la plata',
    deDondeSale: 'De dónde sale la plata',
    quedaEn: (saldo: string) => `queda en ${saldo}`,
    tieneEnLaLista: (saldo: string) => `tiene ${saldo}`,
    entendido: 'Entendido',
    noArchivar: 'No archivar',
    archivar: (nombre: string) => `Archivar ${nombre}`,
    pasarA: (monto: string, destino: string) => `Pasar ${monto} a ${destino} y archivar`,
    pasarDesde: (monto: string, origen: string) => `Pasar ${monto} desde ${origen} y archivar`,
  },
  campos: {
    sinNombre: 'Sin nombre',
    asiSeVe: 'Así se ve',
    nombre: 'Nombre',
    paraQueEs: 'Para qué es',
    opcional: 'Opcional',
    color: 'Color',
    tambienLaUsa: (nombre: string) =>
      `También la usa ${nombre}: se distinguen por el nombre y el ícono.`,
    icono: 'Ícono',
    meta: 'Meta',
    ayudaDeLaMeta: 'Opcional. Si la ponés, Inicio te muestra cuánto falta.',
    rinde: 'Rinde por año (%)',
    ayudaDelRinde: 'Solo sirve para proyectar. Si no lo sabés, dejalo en 0.',
  },
  iconos: {
    receipt: 'Recibo',
    package: 'Paquete',
    'building-2': 'Edificio',
    wrench: 'Llave',
    vault: 'Caja fuerte',
    landmark: 'Banco',
    coins: 'Monedas',
    'trending-up': 'Flecha que sube',
    'piggy-bank': 'Chanchito',
    car: 'Auto',
    truck: 'Camión',
    plane: 'Avión',
    'graduation-cap': 'Birrete',
    gift: 'Regalo',
    shield: 'Escudo',
    sprout: 'Brote',
    house: 'Casa',
    hammer: 'Martillo',
    church: 'Iglesia',
  },
  errores: {
    nombre: (maximo: number) => `Ponele un nombre, de hasta ${String(maximo)} letras.`,
    descripcion: (maximo: number) => `Hasta ${String(maximo)} letras.`,
    rinde: 'Escribí el rinde como un porcentaje, por ejemplo 40. Podés dejarlo en 0.',
    monto: 'Poné hasta cuánto recibe.',
    montoGrande: 'El monto no puede ser tan grande.',
    porcentajeDeLaObligacion: (minimo: string, maximo: string) =>
      `Poné un porcentaje de ${minimo} a ${maximo}.`,
    porcentajeDelReparto: (minimo: string, libre: string) =>
      `Poné un porcentaje de ${minimo} a ${libre}, lo que queda libre.`,
  },
  bajada: {
    conRinde: 'Nombre, color, ícono, meta y rinde',
    conMeta: 'Nombre, color, ícono y meta',
    deSiempre: 'Nombre, color e ícono',
  },
  lugar: {
    alEstante: 'Al estante',
    estante: 'No recibe de los cobros: lo sumás a la fila después',
    obligacion: 'Un porcentaje de cada cobro, como Ingresos Brutos',
    obligacionesLlenas: (tope: number) => `Entran hasta ${String(tope)} obligaciones.`,
    compromiso: 'Junta lo que tenés que pagar, como el alquiler',
    ahorroFijo: 'Un monto fijo que apartás de la ganancia',
    pasosLlenos: (tope: number) => `Entran hasta ${String(tope)} compromisos y ahorros fijos.`,
    repartoLleno: (tope: number) => `El reparto admite hasta ${String(tope)} tesoros.`,
    repartoEnCien: 'El reparto ya suma 100%.',
    reparto: 'Un porcentaje de lo que sobra',
    superavit: (nombre: string) => `Recibe lo que sobra, en lugar de ${nombre}`,
    alFinal: 'Al final de su tipo',
    alPrincipio: 'Al principio de su tipo',
    despuesDe: (nombre: string) => `Después de ${nombre}`,
    elAnterior: 'el anterior',
    libre: (libre: string) => `Queda libre el ${libre}% del reparto.`,
    libreHastaCien: (libre: string, porcentaje: string) =>
      `Queda libre el ${libre}% del reparto: con ${porcentaje}%, el reparto llega al 100%.`,
    libreConResto: (libre: string, porcentaje: string, nombre: string, resto: string) =>
      `Queda libre el ${libre}% del reparto: con ${porcentaje}%, ${nombre} se queda con el otro ${resto}%.`,
  },
  sugerencias: {
    stockDelTaller: 'Stock del taller',
    maquinaria: 'Maquinaria',
    vehiculo: 'Vehículo',
    inmueble: 'Inmueble',
    ingresosBrutos: 'Ingresos Brutos',
    gastosFijos: 'Gastos fijos',
    sueldos: 'Sueldos',
    alquiler: 'Alquiler',
    cuotas: 'Cuotas',
    superavit: 'Superávit',
  },
  nuevo: {
    titulo: 'Nuevo tesoro',
    bajada: 'Un lugar más para la plata',
    sobreQueSeCalcula: 'Sobre qué se calcula',
    nombresSugeridos: 'Nombres sugeridos',
    dondeVa: 'Dónde va',
    porcentaje: 'Porcentaje (%)',
    antesDelDiezmo: 'Antes del diezmo',
    monto: 'Monto',
    ayudaDelCompromiso:
      'Junta hasta eso y se renueva al pagar: cuando registrás el pago, vuelve a juntar.',
    ayudaDelAhorroFijo: 'Recibe hasta eso por mes. Lo que pasa de eso sigue abajo.',
    porcentajeDeLoQueSobra: 'Porcentaje de lo que sobra (%)',
    crear: 'Crear el tesoro',
  },
  editar: {
    archivar: 'Archivar',
    guardar: 'Guardar',
  },
} as const;
