export const movimiento = {
  dolares: 'Dólares',
  grupos: {
    ingreso: 'Ingreso',
    gasto: 'Gasto',
    diezmo: 'Diezmo',
    cocos: 'Cocos',
    entre: 'Entre tesoros',
    dolares: 'Dólares',
  },
  clases: {
    ingresoHogar: {
      etiqueta: 'Ingreso al hogar',
      corta: 'Al hogar',
      ejemplo: 'Docencia de septiembre',
    },
    ingresoMaun: {
      etiqueta: 'Ingreso al taller',
      corta: 'Al taller',
      ejemplo: 'Venta de recortes de melamina',
    },
    gastoHogar: {
      etiqueta: 'Gasto del hogar',
      corta: 'Del hogar',
      ejemplo: 'Supermercado, luz y gas, pediatra…',
    },
    gastoMaun: {
      etiqueta: 'Gasto del taller',
      corta: 'Del taller',
      ejemplo: 'Alquiler, hoja de sierra, seguro…',
    },
    gastoTesoro: {
      etiqueta: 'Gasto de un tesoro',
      corta: 'De un tesoro',
      ejemplo: 'El alquiler de septiembre',
    },
    pagoDiezmo: {
      etiqueta: 'Pago de diezmo',
      corta: 'Pago de diezmo',
      ejemplo: 'Diezmo de septiembre',
    },
    aporteCocos: {
      etiqueta: 'Del taller a Cocos',
      corta: 'Aporte',
      ejemplo: 'Aporte del mes',
    },
    retiroCocos: {
      etiqueta: 'De Cocos al taller',
      corta: 'Retiro',
      ejemplo: 'Retiro para comprar la plegadora',
    },
    gastoCocos: {
      etiqueta: 'Gasto desde Cocos',
      corta: 'Gasto',
      ejemplo: 'Seña del terreno',
    },
    entreTesoros: {
      etiqueta: 'Entre tesoros',
      corta: 'Entre tesoros',
      ejemplo: 'Para los materiales del mes',
    },
    compraDeDolares: {
      etiqueta: 'Compra de dólares',
      corta: 'Compra',
      ejemplo: 'El ahorro del mes',
    },
    ventaDeDolares: {
      etiqueta: 'Venta de dólares',
      corta: 'Venta',
      ejemplo: 'Para pagar el alquiler',
    },
    ingresoEnDolares: {
      etiqueta: 'Ingreso en dólares',
      corta: 'Ingreso',
      ejemplo: 'Los que tenía guardados',
    },
  },
  categorias: {
    Docencia: 'Docencia',
    Changas: 'Changas',
    Regalos: 'Regalos',
    'Venta personal': 'Venta personal',
    'Cobro suelto': 'Cobro suelto',
    'Venta de sobrantes': 'Venta de sobrantes',
    Supermercado: 'Supermercado',
    Servicios: 'Servicios',
    Salud: 'Salud',
    Educación: 'Educación',
    Transporte: 'Transporte',
    Ropa: 'Ropa',
    Recreación: 'Recreación',
    Iglesia: 'Iglesia',
    Materiales: 'Materiales',
    Herramientas: 'Herramientas',
    'Costos fijos': 'Costos fijos',
    'Gasto fijo': 'Gasto fijo',
    Flete: 'Flete',
    'Servicios del taller': 'Servicios del taller',
    Publicidad: 'Publicidad',
    Compra: 'Compra',
    Imprevisto: 'Imprevisto',
    Regalo: 'Regalo',
    'Compra del inmueble': 'Compra del inmueble',
    'Escritura y sellos': 'Escritura y sellos',
    Mudanza: 'Mudanza',
    Oficial: 'Oficial',
    MEP: 'MEP',
    Blue: 'Blue',
    Cripto: 'Cripto',
    'Ahorro previo': 'Ahorro previo',
    Otro: 'Otro',
    Cobro: 'Cobro',
    Distribución: 'Distribución',
    Apertura: 'Apertura',
    Ajuste: 'Ajuste',
    'Archivo de un tesoro': 'Archivo de un tesoro',
    'Cubrir el mes': 'Cubrir el mes',
  },
  ayuda: {
    ingresoHogar: 'Entra al hogar y no pasa por el taller ni por el diezmo.',
    ingresoMaun:
      'Entra a la caja del taller. Esto es para un cobro suelto: lo que viene de un trabajo cargado se anota en el trabajo, así queda atado a su reparto.',
    gastoHogar: 'Sale del hogar.',
    gastoMaun:
      'Sale de la caja del taller. Si es de un mueble puntual conviene cargarlo como gasto del trabajo, así se descuenta del ingreso de ese trabajo.',
    pagoDiezmo: 'Sale de lo que el diezmo tiene apartado.',
    aporteCocos: 'Pasa de la caja del taller al fondo de Cocos.',
    retiroCocos:
      'Sale de Cocos y vuelve a la caja del taller: no se va del taller, cambia de bolsillo.',
    gastoCocos: 'Sale de Cocos y se va.',
    gastoTesoro: (tesoro: string) => `Sale de ${tesoro} y se va.`,
    gastoTesoroSinElegir: 'Sale del tesoro que elijas y se va.',
    entreTesoros: (desde: string, hacia: string) =>
      `Pasa de ${desde} a ${hacia}: la plata no se va, cambia de bolsillo.`,
    entreTesorosSinElegir: 'Pasa de un tesoro a otro: la plata no se va, cambia de bolsillo.',
    elHogarQueda: (saldo: string) => `El hogar queda en ${saldo}.`,
    elHogarQuedaEnNegativo: (saldo: string) => `El hogar queda en ${saldo}, o sea en negativo.`,
    elTallerQueda: (saldo: string) => `El taller queda en ${saldo}.`,
    elTallerQuedaEnNegativo: (saldo: string) => `El taller queda en ${saldo}, o sea en negativo.`,
    cocosQueda: (saldo: string) => `Cocos queda en ${saldo}.`,
    cocosQuedaEnNegativo: (saldo: string) => `Cocos queda en ${saldo}, o sea en negativo.`,
    cocosQuedaDeLaMeta: (saldo: string, meta: string) =>
      `Cocos queda en ${saldo} de la meta de ${meta}.`,
    teVanAQuedarPorPagar: (saldo: string) =>
      `Después de este pago te van a quedar ${saldo} por pagar.`,
    tePasas: (saldo: string) => `Con este pago te pasás ${saldo}.`,
    quedasAlDia: 'Con este pago quedás al día.',
    compra: 'Cambia pesos por dólares: la plata no se va, cambia de moneda.',
    venta: 'Cambia dólares por pesos: la plata no se va, cambia de moneda.',
    quedan: (desde: string, quedaDesde: string, hacia: string, quedaHacia: string) =>
      `${desde} queda en ${quedaDesde}, y ${hacia} en ${quedaHacia}.`,
    quedanConElPrimeroEnNegativo: (
      desde: string,
      quedaDesde: string,
      hacia: string,
      quedaHacia: string,
    ) => `${desde} queda en ${quedaDesde}, o sea en negativo, y ${hacia} en ${quedaHacia}.`,
    ingresoEnDolares:
      'Entra al tesoro en dólares que elijas y no pasa por el taller ni por el diezmo.',
    entraA: (tesoro: string) => `Entra a ${tesoro} y no pasa por el taller ni por el diezmo.`,
    queda: (tesoro: string, saldo: string) => `${tesoro} queda en ${saldo}.`,
    quedaEnNegativo: (tesoro: string, saldo: string) =>
      `${tesoro} queda en ${saldo}, o sea en negativo.`,
  },
  diezmo: {
    debes: 'Debés',
    debesElImporte: (importe: string) => `Debés ${importe}`,
    deLoQueYaCobraste: 'de lo que ya cobraste y todavía no diste',
    pagasteDeMas: 'Pagaste de más',
    pagasteElImporteDeMas: (importe: string) => `Pagaste ${importe} de más`,
    seDescuenta: 'se descuenta de lo próximo que se genere',
    estasAlDia: 'Estás al día',
    todoPagado: 'todo lo generado ya está pagado',
  },
  resumenDelMes: {
    entroAlHogar: 'Entró al hogar',
    gastoElHogar: 'Gastó el hogar',
    facturoElTaller: 'Facturó el taller',
  },
  libro: {
    motivoDelBloqueo: {
      'del-proyecto':
        'Este asiento lo genera el proyecto: sale de sus pagos, de sus gastos y del reparto que quedó congelado al cobrarlo. Para cambiarlo hay que corregir el proyecto.',
      ajuste:
        'Un ajuste no se edita: es la constancia de una corrección que ya se hizo. Si quedó mal, se compensa con otro ajuste en sentido contrario.',
    },
    etiquetaDerivada: {
      cobro: 'Cobro del trabajo',
      gasto: 'Gasto del trabajo',
      diezmo: 'Diezmo del reparto',
      sueldo: 'Sueldo del reparto',
      fijos: 'Gastos fijos del reparto',
      prioridad: 'Paso del reparto',
      reparto: 'Parte del reparto',
    },
    delTrabajo: 'Del trabajo',
    ajusteDeSaldo: 'Ajuste de saldo',
    movimiento: 'Movimiento',
    otroTesoro: 'Otro tesoro',
    yaEstabaEnTusSaldos: 'ya estaba en tus saldos',
    sinConfirmar: 'sin confirmar',
    sinEfectoEnLosSaldos: 'sin efecto en los saldos',
  },
  ficha: {
    fecha: 'Fecha',
    saleDe: 'Sale de',
    entraA: 'Entra a',
    categoria: 'Categoría',
    deAfueraDelTaller: 'de afuera del taller',
    seVaDelTaller: 'se va del taller',
    yaEnLaApertura:
      'Es de antes de que empezaras con la app: esta plata ya estaba en tus saldos, así que queda anotada con su fecha pero no mueve los tesoros.',
    editar: 'Editar',
    borrar: 'Borrar',
    verElTrabajo: (titulo: string) => `Ver «${titulo}»`,
    verElTrabajoSinTitulo: 'Ver «el trabajo»',
  },
  casillaDeLaApertura: 'Esta plata ya estaba en tus saldos cuando empezaste con la app',
  cambioEnElLibro: (sale: string, entra: string, cotizacion: string) =>
    `${sale} → ${entra} · a ${cotizacion}`,
  equivalenteDeLaCompra: (pesos: string, cotizacion: string, fecha: string) =>
    `≈ ${pesos} a ${cotizacion}, tu última compra (${fecha})`,
  equivalenteDeLaVenta: (pesos: string, cotizacion: string, fecha: string) =>
    `≈ ${pesos} a ${cotizacion}, tu última venta (${fecha})`,
  comprarDolares: 'Comprar dólares',
  venderDolares: 'Vender dólares',
} as const;
