export const paginaProyectos = {
  comun: {
    proyectos: 'Proyectos',
    volverAProyectos: 'Volver a Proyectos',
    noEsta: 'Ese proyecto no está',
    noEstaTexto:
      'Puede que lo hayas borrado desde otro dispositivo, o que el enlace apunte a un proyecto de otro taller.',
    mostrarleAlCliente: 'Mostrarle al cliente',
    editar: 'Editar',
    contactarA: (cliente: string) => `Contactar a ${cliente}`,
    darPorPerdido: 'Dar por perdido',
    siNoSale: 'Si no sale',
    notas: 'Notas',
    notasEjemplo: 'Lo que te dijo por teléfono, medidas, cómo llegar…',
    presupuesto: 'Presupuesto',
    todaviaSinPresupuesto: 'Todavía sin presupuesto',
    senaCobrada: 'Seña cobrada',
    sinSena: 'Sin seña',
    telefono: 'Teléfono',
    sinTelefono: 'Sin teléfono',
    estabaEn: 'Estaba en',
    cobrado: 'Cobrado',
    saldo: 'Saldo',
    sinSaldo: 'Sin saldo',
    todos: 'Todos',
    buscarPorClienteOTrabajo: 'Buscar por cliente o trabajo',
    limpiarLaBusqueda: 'Limpiar la búsqueda',
    fechaYCuando: (fecha: string, cuando: string) => `${fecha}, ${cuando}`,
  },
  ficha: {
    fechas: {
      inicio: 'Inicio',
      listo: 'Listo',
      entregaEstimada: 'Entrega estimada',
      entregaComprometida: 'Entrega comprometida',
      entregado: 'Entregado',
      cerrado: 'Cerrado',
      cobrado: 'Cobrado',
    },
    recienAprobado: 'Pasó de Consultas a Activos, con lo que ya habías cobrado adentro.',
    cobrarElSaldo: (saldo: string) => `Cobrar el saldo de ${saldo}`,
    cobrarYRepartir: 'Cobrar y repartir',
    pagosRecibidos: 'Pagos recibidos',
    cuantosPagos: (pagos: number) => (pagos === 1 ? '1 pago' : `${String(pagos)} pagos`),
    sinPagos: 'Todavía no cobraste nada de este proyecto. La seña suele ir primero.',
    pago: 'Pago',
    gastosEInsumos: 'Gastos e insumos',
    cuantosGastos: (gastos: number) => (gastos === 1 ? '1 ítem' : `${String(gastos)} ítems`),
    sinGastos:
      'Sin gastos cargados. Todo lo que compres para este mueble va acá y se descuenta del ingreso del trabajo.',
    insumo: 'Insumo',
    totalDeGastos: 'Total de gastos',
    cargarPagosYGastos: 'Cargar pagos y gastos',
    congelados: {
      cobrado:
        'Este proyecto está cobrado: sus pagos y sus gastos quedaron congelados con la distribución.',
      perdido:
        'Este proyecto está perdido: sus pagos y sus gastos quedaron congelados con la distribución.',
    },
    entregaYComprobante: 'Entrega y comprobante',
    direccionDeEntrega: 'Dirección de entrega',
    sinDireccion: 'Sin dirección',
    otraDireccion: 'Distinta del domicilio del cliente',
    abrirEnElMapa: 'Abrir en el mapa',
    comprobante: 'Comprobante a emitir',
    formaDePago: 'Forma de pago',
    sinDefinir: 'Sin definir',
    notasDeObra: 'Notas de obra',
    notasDeObraEjemplo: 'Medidas, qué falta, qué hablar con el cliente…',
  },
  contacto: {
    consultas: 'Consultas',
    sinFecha: 'Sin fecha',
    vencioEl: (fecha: string) => `Venció el ${fecha}`,
    datosDelContacto: 'Datos del contacto',
    relevamiento: 'Relevamiento',
    visita: 'Visita',
    cambiarElRelevamiento: 'Cambiar el día del relevamiento',
    cambiarLaVisita: 'Cambiar el día de la visita',
    cambiar: 'Cambiar',
    valeHasta: 'Vale hasta',
    cambiarLaVigencia: 'Cambiar hasta cuándo vale el presupuesto',
    presupuestoAntesDel: 'Presupuesto antes del',
    sinFechaLimite: 'Sin fecha límite',
    gastosCargados: 'Gastos cargados',
    yaEntroALaCaja:
      'La seña ya entró a la caja del taller y los gastos ya salieron: se ven en Finanzas desde el día que los cargaste.',
    cargarOtroPago: 'Cargar otro pago o un gasto',
    siNoSaleConSena: (sena: string) =>
      `Si te dijo «por ahora no», pasalo a seguimiento con el día en que le volvés a escribir: sale de tus consultas y la agenda te avisa. Si no va, la seña de ${sena} se liquida como ingreso del taller, y el contacto pasa al historial. Se puede reactivar.`,
    siNoSaleSinSena:
      'Si te dijo «por ahora no», pasalo a seguimiento con el día en que le volvés a escribir: sale de tus consultas y la agenda te avisa. Si no va, pasa al historial sin mover plata. Se puede reactivar.',
    porAhoraNo: 'Por ahora no',
  },
  seguimiento: {
    seguimiento: 'Seguimiento',
    sinDia: 'Sin día para volver a escribirle',
    hoy: 'Hoy le volvés a escribir',
    leTocaba: (fecha: string) => `Le tocaba el ${fecha}`,
    leVolvesAEscribir: (fecha: string) => `Le volvés a escribir el ${fecha}`,
    proximoContacto: 'Próximo contacto',
    registrarElContacto: 'Registrar el contacto',
    cuandoLeEscribas:
      'Cuando le escribas, registralo: ahí elegís si vuelve a las consultas, si sigue en seguimiento con otra fecha o si no va.',
    datosDelTrabajo: 'Datos del trabajo',
    historia: 'Historia del seguimiento',
    sinHistoria: 'Todavía no le volviste a escribir desde que pasó a seguimiento.',
    siNoSaleConSena: (sena: string) =>
      `La seña de ${sena} se liquida como ingreso del taller, y el trabajo pasa al historial. Se puede reactivar.`,
    siNoSaleSinSena: 'Pasa al historial sin mover plata. Se puede reactivar.',
  },
  lista: {
    metricas: {
      proyectos: 'proyectos',
      enCurso: 'en curso',
      entregadosConSaldo: 'entregados con saldo',
      cobrados: 'cobrados',
    },
    ordenarPor: 'Ordenar por',
    vacio: {
      activos: {
        titulo: 'Todavía no hay proyectos activos',
        detalle:
          'Acá están los trabajos que te aprobaron. Los contactos y los presupuestos que esperan respuesta viven en Consultas, y pasan solos a esta pestaña cuando los aprobás.',
      },
      historial: {
        titulo: 'Todavía no cerraste ningún proyecto',
        detalle:
          'Cuando cobres el primero, acá va a quedar el historial con lo que ganaste en cada uno.',
      },
    },
    cargarUnProyecto: 'Cargar un proyecto',
    cargarContacto: 'Cargar contacto',
    nuevoProyecto: 'Nuevo proyecto',
    etapa: 'Etapa',
    buscarPorCliente: 'Buscar por cliente',
    ordenar: 'Ordenar',
    ningunoCoincide: (busqueda: string) => `Ningún proyecto coincide con «${busqueda}».`,
    ningunoEnEseEstado: 'Ningún proyecto está en ese estado.',
  },
  consultas: {
    visita: 'Visita',
    vacioTitulo: 'No hay consultas por ahora',
    vacioDetalle:
      'Cuando te llame alguien, cargalo acá con lo que pide y la fecha de la visita. Si en la visita te dejó una seña, anotala: entra a la caja del taller desde ese día. Cuando lo apruebe, pasa a Activos.',
    cargarElPrimero: 'Cargar el primer contacto',
    buscarContacto: 'Buscar contacto',
    ningunoCoincide: (busqueda: string) => `Ningún contacto coincide con «${busqueda}».`,
    ningunoEnEsaEtapa: 'Ningún contacto está en esa etapa.',
    orden: 'Primero lo que hace más que espera; las visitas agendadas, al final.',
    contactos: 'Contactos',
  },
  listaDeSeguimiento: {
    sinFecha: 'Sin fecha para volver a escribirle',
    leTocaHoy: 'Le toca hoy',
    atrasado: (fecha: string, cuando: string) => `Atrasado: le tocaba el ${fecha}, ${cuando}`,
    elDia: (fecha: string, cuando: string) => `El ${fecha}, ${cuando}`,
    volverAEscribirle: 'Volver a escribirle',
    vacioTitulo: 'Nadie en seguimiento',
    vacioDetalle:
      'Cuando una consulta te diga «por ahora no», pasala a seguimiento desde su ficha con el día en que le volvés a escribir. Acá quedan en orden, los atrasados primero, y la agenda te avisa cuándo toca.',
    buscarEnSeguimiento: 'Buscar en seguimiento',
    nadieCoincide: (busqueda: string) => `Nadie en seguimiento coincide con «${busqueda}».`,
    orden: 'Por el día en que le volvés a escribir: los atrasados, primero.',
    enSeguimiento: 'En seguimiento',
  },
  insumos: {
    insumosDelTrabajo: 'Insumos del trabajo',
    insumos: 'Insumos',
    enMaun: 'en Maun hasta que se cobre',
    entro: 'Entró',
    gastado: 'Gastado',
    queda: 'Queda',
    nada: 'Nada',
  },
  analitico: 'Analítico de entregas',
  presupuesto: {
    volverAlTrabajo: 'Volver al trabajo',
    yaNoSeCambia: 'Este presupuesto ya no se cambia',
    yaNoSeCambiaTexto:
      'El trabajo ya está aprobado o cerrado. Lo que le mandaste queda en la ficha, con su PDF.',
  },
  vistaCliente: {
    volverAlTrabajo: 'Volver al trabajo',
    volverA: (trabajo: string) => `Volver a «${trabajo}»`,
    sinSenal: 'Sin señal: esto es lo último que trajimos. Puede no estar al día.',
  },
} as const;
