export const registrarMovimiento = {
  editar: 'Editar el movimiento',
  cargar: 'Cargar un movimiento',
  tipo: 'Tipo',
  detalleDelTipo: 'Detalle del tipo',
  cubreElMes: (mes: string) =>
    `Cubre lo que faltaba para los gastos fijos de ${mes}, así que sigue siendo un pase entre tesoros.`,
  saleDe: 'Sale de',
  entraA: 'Entra a',
  cuantaPlata: 'Cuánta plata',
  categoria: 'Categoría',
  queFue: 'Qué fue',
  cuando: 'Cuándo',
  hoy: 'Hoy',
  ayer: 'Ayer',
  otraFecha: 'Otra fecha',
  faltanLosLados: 'Elegí de qué tesoro sale la plata y a cuál entra.',
  faltaElTesoro: 'Elegí de qué tesoro sale la plata.',
  faltaElMonto: 'Escribí cuánta plata es, por ejemplo 12.500.',
  seVaABorrar: (monto: string) =>
    `Se va a borrar este movimiento de ${monto} y los saldos se recalculan sin él.`,
  borrarlo: 'Borrarlo',
  dejarlo: 'Dejarlo',
  quedaEnLaCola: 'Queda en la cola: se sincroniza cuando vuelva la señal.',
  borrar: 'Borrar',
  guardarLosCambios: 'Guardar los cambios',
  cargarElMovimiento: 'Cargar el movimiento',
  cambio: {
    salenDe: 'Salen de',
    entranA: 'Entran a',
    pagaste: 'Pagaste',
    vendiste: 'Vendiste',
    recibiste: 'Recibiste',
    queDolar: 'Qué dólar',
    teQuedoA: (cotizacion: string) => `Te quedó a ${cotizacion} por dólar.`,
    teLoPagaronA: (cotizacion: string) => `Te lo pagaron a ${cotizacion} por dólar.`,
    faltaLoQuePagaste: 'Escribí cuánto pagaste.',
    faltaLoQueVendiste: 'Escribí cuánto vendiste.',
    faltaLoQueRecibiste: 'Escribí cuánto recibiste.',
  },
} as const;
