import type { Mensajes } from '../es';

export const appNavegacion = {
  pantallas: {
    inicio: 'Início',
    agenda: 'Agenda',
    consultas: 'Consultas',
    seguimiento: 'Retornos',
    proyectos: 'Projetos',
    historial: 'Histórico',
    proyectoNuevo: 'Novo projeto',
    analitico: 'Análise das entregas',
    editarProyecto: 'Editar projeto',
    presupuesto: 'Orçamento',
    aprobar: 'Aprovar',
    mostrarleAlCliente: 'Mostrar ao cliente',
    loQueVeElCliente: 'Como o cliente vê',
    cobrar: 'Receber',
    darPorPerdido: 'Marcar como perdido',
    clientes: 'Clientes',
    finanzas: 'Finanças',
    tesoros: 'Caixinhas',
    opiniones: 'Opiniões',
    diezmo: 'Dízimo',
    estadisticas: 'Estatísticas',
    ajustes: 'Configurações',
    avisos: 'Notificações',
    tuPresupuesto: 'Seu orçamento',
    facturacion: 'Faturamento',
    conectarConArca: 'Conectar com a ARCA',
  },
} satisfies Mensajes['appNavegacion'];
