import type { Mensajes } from '../es';

export const editarCliente = {
  editar: 'Editar cliente',
  nuevo: 'Novo cliente',
  nombre: 'Nome',
  comoLoTenesAgendado: 'Como está nos seus contatos',
  telefono: 'Telefone',
  zona: 'Região',
  localidadOBarrio: 'Cidade ou bairro',
  email: 'E-mail',
  opcional: 'Opcional',
  direccion: 'Endereço',
  calleYNumero: 'Rua e número, cidade',
  comoLlego: 'Como chegou',
  sinEspecificar: 'Não informado',
  quienLoRefirio: 'Quem indicou',
  detalle: 'Detalhe',
  nombreDeQuienLoRecomendo: 'Nome de quem indicou',
  loQueQuierasAnotar: 'O que você quiser anotar',
  condicionFrenteAlIva: 'Condição perante o IVA',
  condicionYComprobante: (condicion, comprobante) => `${condicion}. Você emite ${comprobante}.`,
  dni: 'DNI',
  dniParaFacturar: (umbral) =>
    `É necessário para emitir nota fiscal de projetos de ${umbral} ou mais.`,
  cuit: 'CUIT',
  cuitParaFacturar: 'Se o cliente pedir a nota fiscal com o CUIT dele.',
  razonSocial: 'Razão social',
  siFacturaAUnaEmpresa: 'Se faturar para uma empresa',
  domicilioFiscal: 'Endereço fiscal',
  siEsDistinto: 'Se for diferente do endereço',
  notas: 'Notas',
  loQueConvengaRecordar: 'O que vale lembrar deste cliente',
  cancelar: 'Cancelar',
  guardarLosCambios: 'Salvar alterações',
  guardarCliente: 'Salvar cliente',
} satisfies Mensajes['editarCliente'];
