import type { Mensajes } from '../es';

import { plural } from './plural';

export const editarProyecto = {
  pantalla: {
    cancelar: 'Cancelar',
    proyectoNuevo: 'Novo projeto',
    editarProyecto: 'Editar projeto',
    trabajo: 'Projeto',
    trabajoEjemplo: 'Guarda-roupa de 3 portas, bancada de cozinha…',
    tipo: 'Tipo de projeto',
    tipoEjemplo: 'Cozinha, guarda-roupa, closet…',
    tipoAyuda:
      'Com o tipo, a Análise das entregas mostra quanto tempo você leva em cada tipo de móvel.',
    presupuesto: 'Orçamento',
    sinDefinir: 'Não definido',
    presupuestoDeLaOpcion:
      'Vem da opção que você marcar abaixo. Para digitar à mão, tire as opções.',
    presupuestoVacio: 'Deixe vazio enquanto não estiver orçado.',
    senaPropia: 'Sinal próprio (%)',
    senaDelTaller: 'O da marcenaria',
    senaAyuda:
      'Deixe vazio para pedir o sinal de sempre. Preencha só se para este você pedir outro.',
    formaDePago: 'Forma de pagamento',
    fechaDeInicio: 'Data de início',
    entregaEstimada: 'Previsão de entrega',
    entregaCalculada: 'Calculada em 21 dias úteis a partir do início.',
    horaDeLaEntrega: 'Horário da entrega',
    horaAyuda: 'Opcional. Com horário, a entrega aparece na linha do dia na agenda.',
    estado: 'Status',
    estadoCongelado: {
      cobrado: 'Um projeto pago tem a divisão congelada: para mudar o status, reabra o projeto.',
      perdido: 'Um projeto perdido tem a divisão congelada: para mudar o status, reabra o projeto.',
    },
    direccionDeEntrega: 'Endereço de entrega',
    usarLaDelCliente: 'Usar o do cliente',
    direccionEjemplo: 'Rua e número, cidade',
    abrirLaDireccion: 'Abrir o endereço no mapa',
    comprobante: 'Comprovante a emitir',
    porLaCondicion: (condicion) => `Situação fiscal: ${condicion}`,
    notasDeObra: 'Notas do projeto',
    notasEjemplo: 'Medidas, o que falta, o que conversar com o cliente…',
    repartoCerrado: {
      cobrado:
        'Este projeto está pago e a divisão foi fechada: os pagamentos e as despesas não podem ser alterados.',
      perdido:
        'Este projeto está perdido e a divisão foi fechada: os pagamentos e as despesas não podem ser alterados.',
    },
    reactivarlo: 'Reativar para poder registrar',
    reabrirElCobro: 'Reabrir o recebimento para corrigir',
    alGuardarLoCierra:
      'Os campos são liberados aqui mesmo. Ao salvar, você volta para fechar de novo, com o sinal dividido contando o que registrou.',
    alGuardarLoCobra:
      'Os campos são liberados aqui mesmo. Ao salvar, você volta para receber de novo, com a divisão refeita.',
    totales: {
      presupuesto: 'Orçamento',
      cobrado: 'Recebido',
      saldo: 'Saldo',
      neta: 'Líquido',
    },
    guardarProyecto: 'Salvar projeto',
    guardarLosCambios: 'Salvar alterações',
  },
  filas: {
    pagos: {
      titulo: 'Pagamentos recebidos',
      detalle: (fila) => `Descrição do pagamento ${String(fila)}`,
      quitar: (fila) => `Remover pagamento ${String(fila)}`,
      placeholder: 'Sinal, adiantamento, saldo…',
      agregar: 'Adicionar um pagamento',
      ayuda: 'O que o cliente pagou por este projeto. Entra no caixa da marcenaria.',
      vacio: 'Você ainda não recebeu nada deste projeto. O sinal costuma vir primeiro.',
    },
    gastos: {
      titulo: 'Despesas e insumos',
      detalle: (fila) => `Descrição da despesa ${String(fila)}`,
      quitar: (fila) => `Remover despesa ${String(fila)}`,
      placeholder: 'Melamina, ferragens, frete…',
      agregar: 'Adicionar uma despesa',
      ayuda: 'Materiais e compras deste móvel. São descontados da receita do projeto.',
      vacio: 'Você ainda não registrou despesas para este móvel.',
    },
    fecha: (fila) => `Data ${String(fila)}`,
    monto: (fila) => `Valor ${String(fila)}`,
    quiteLaFila: 'Removi a linha.',
    quite: (quitado) => `Removi ${quitado}.`,
    deshacer: 'Desfazer',
  },
  opciones: {
    titulo: 'Opções que você apresentou',
    aprobada: (monto) => `Aprovada: ${monto}`,
    ayuda:
      'Os orçamentos que você apresentou. Marque o que o cliente aprovou e ele passa a ser o orçamento do projeto.',
    agregar: 'Adicionar uma opção',
    sinOpciones: 'Sem opções. Se você passar um preço só, registre acima em Orçamento.',
    queIncluye: (opcion) => `O que a opção ${String(opcion)} inclui`,
    queIncluyeEjemplo: 'Só a escrivaninha, as 2 escrivaninhas…',
    estaAprobada: 'Aprovada',
    laAprobo: 'Aprovar',
    importe: (opcion) => `Valor da opção ${String(opcion)}`,
    quitar: (opcion) => `Remover a opção ${String(opcion)}`,
    quiteLaOpcion: 'Removi a opção.',
    quite: (quitado) => `Removi ${quitado}.`,
    deshacer: 'Desfazer',
  },
  opcionesDelTrabajo: {
    titulo: 'Opções de orçamento',
    cargarLaPrimera:
      'Se você apresentar mais de uma variante, registre cada uma com o valor. Quando o cliente escolher, marque a que ele aprovou.',
    cargarLasOpciones: 'Registrar as opções',
    aprobaste: (monto) => `Você aprovou ${monto}: é o orçamento do projeto.`,
    sacasteLaAprobacion: 'Você tirou a aprovação: o projeto fica sem orçamento.',
    deshacer: 'Desfazer',
    cuantas: (opciones) => plural(opciones, { one: '# opção', other: '# opções' }),
    sinAprobar: 'Marque a que o cliente aprovou e esse valor passa a ser o orçamento do projeto.',
    conAprobada: 'As que ele não escolheu ficam aqui, para você saber o que ofereceu.',
    sinDetalle: 'Opção sem detalhe',
    esElPresupuesto: 'Aprovada: é o orçamento do projeto',
    estaAprobada: 'Aprovada',
    laAprobo: 'Aprovar',
  },
  borrado: {
    borrar: 'Excluir',
    pregunta: (trabajo) => `Excluir “${trabajo}”?`,
    sinPlataDelContacto: 'Não tem sinal nem despesas registradas, então nenhum dinheiro se move.',
    sinPlataDelProyecto:
      'Não tem pagamentos nem despesas registradas, então nenhum dinheiro se move.',
    conPlata: (pagos, gastos) =>
      `Vai levar junto ${plural(pagos, { '=0': 'nenhum pagamento', one: '# pagamento', other: '# pagamentos' })} e ${plural(gastos, { '=0': 'nenhuma despesa', one: '# despesa', other: '# despesas' })}, e eles saem do livro-caixa.`,
    cancelar: 'Cancelar',
    borrarElContacto: 'Excluir contato',
    borrarElProyecto: 'Excluir projeto',
  },
  avance: {
    titulo: 'O que falta',
    yaEstaListo: 'Marcar como pronto',
    todaviaNoEstaListo: 'Desmarcar como pronto',
  },
  loQueHaceFalta: {
    titulo: 'O que é preciso',
    ayuda:
      'Os materiais e as ferragens que é preciso pedir, e as ferramentas que é preciso ter no dia em que você fizer. Aparecem sugestões do que você já usou.',
    todoListo: 'tudo pronto',
    listas: (listas, cuantas) => `${String(listas)} de ${String(cuantas)}`,
    cosas: (cosas) => plural(cosas, { one: '# item', other: '# itens' }),
    cerrado: 'Este projeto está fechado: a lista fica como ficou.',
    saque: (necesidad) => `Removi ${necesidad} da lista.`,
    deshacer: 'Desfazer',
    loQueMasUsas: 'O que você mais usa',
    yaLoUsasteAntes: 'Você já usou antes',
    trabajos: (trabajos) => plural(trabajos, { one: '# projeto', other: '# projetos' }),
    cantidadDe: (necesidad) => `Quantidade de ${necesidad}`,
    nombreDe: (necesidad) => `Nome de ${necesidad}`,
    sacarDeLaLista: (necesidad) => `Tirar ${necesidad} da lista`,
  },
} satisfies Mensajes['editarProyecto'];
