import type { Mensajes } from '../es';

export const movimiento = {
  dolares: 'Dólares',
  grupos: {
    ingreso: 'Receita',
    gasto: 'Despesa',
    diezmo: 'Dízimo',
    cocos: 'Cocos',
    entre: 'Entre caixinhas',
    dolares: 'Dólares',
  },
  clases: {
    ingresoHogar: {
      etiqueta: 'Receita da casa',
      corta: 'Para a casa',
      ejemplo: 'Aulas de setembro',
    },
    ingresoMaun: {
      etiqueta: 'Receita da marcenaria',
      corta: 'Para a marcenaria',
      ejemplo: 'Venda de retalhos de melamina',
    },
    gastoHogar: {
      etiqueta: 'Despesa da casa',
      corta: 'Da casa',
      ejemplo: 'Supermercado, luz e gás, pediatra…',
    },
    gastoMaun: {
      etiqueta: 'Despesa da marcenaria',
      corta: 'Da marcenaria',
      ejemplo: 'Aluguel, lâmina de serra, seguro…',
    },
    gastoTesoro: {
      etiqueta: 'Despesa de uma caixinha',
      corta: 'De uma caixinha',
      ejemplo: 'O aluguel de setembro',
    },
    pagoDiezmo: {
      etiqueta: 'Pagamento do dízimo',
      corta: 'Pagamento do dízimo',
      ejemplo: 'Dízimo de setembro',
    },
    aporteCocos: {
      etiqueta: 'Da marcenaria para Cocos',
      corta: 'Aporte',
      ejemplo: 'Aporte do mês',
    },
    retiroCocos: {
      etiqueta: 'De Cocos para a marcenaria',
      corta: 'Retirada',
      ejemplo: 'Retirada para comprar a máquina nova',
    },
    gastoCocos: {
      etiqueta: 'Despesa de Cocos',
      corta: 'Despesa',
      ejemplo: 'Sinal do terreno',
    },
    entreTesoros: {
      etiqueta: 'Entre caixinhas',
      corta: 'Entre caixinhas',
      ejemplo: 'Para os materiais do mês',
    },
    compraDeDolares: {
      etiqueta: 'Compra de dólares',
      corta: 'Compra',
      ejemplo: 'Reserva do mês',
    },
    ventaDeDolares: {
      etiqueta: 'Venda de dólares',
      corta: 'Venda',
      ejemplo: 'Para pagar o aluguel',
    },
    ingresoEnDolares: {
      etiqueta: 'Receita em dólares',
      corta: 'Receita',
      ejemplo: 'Dólares que eu já tinha',
    },
  },
  categorias: {
    Docencia: 'Aulas',
    Changas: 'Bicos',
    Regalos: 'Presentes',
    'Venta personal': 'Venda pessoal',
    'Cobro suelto': 'Recebimento avulso',
    'Venta de sobrantes': 'Venda de sobras',
    Supermercado: 'Supermercado',
    Servicios: 'Serviços',
    Salud: 'Saúde',
    Educación: 'Educação',
    Transporte: 'Transporte',
    Ropa: 'Roupas',
    Recreación: 'Lazer',
    Iglesia: 'Igreja',
    Materiales: 'Materiais',
    Herramientas: 'Ferramentas',
    'Costos fijos': 'Custos fixos',
    Flete: 'Frete',
    'Servicios del taller': 'Serviços da marcenaria',
    Publicidad: 'Publicidade',
    Compra: 'Compra',
    Imprevisto: 'Imprevisto',
    Regalo: 'Presente',
    'Compra del inmueble': 'Compra do imóvel',
    'Escritura y sellos': 'Escritura e impostos',
    Mudanza: 'Mudança',
    Oficial: 'Oficial',
    MEP: 'MEP',
    Blue: 'Blue',
    Cripto: 'Cripto',
    'Ahorro previo': 'Reserva anterior',
    Otro: 'Outro',
    Cobro: 'Recebimento',
    Distribución: 'Divisão',
    Apertura: 'Saldos iniciais',
    Ajuste: 'Ajuste',
    'Archivo de un tesoro': 'Arquivamento de caixinha',
    'Cubrir el mes': 'Cobertura do mês',
  },
  ayuda: {
    ingresoHogar: 'Entra na casa, sem passar pela marcenaria nem pelo dízimo.',
    ingresoMaun:
      'Entra no caixa da marcenaria. Isto é para um recebimento avulso: o que vem de um projeto cadastrado é registrado no projeto, assim fica vinculado à divisão dele.',
    gastoHogar: 'Sai da casa.',
    gastoMaun:
      'Sai do caixa da marcenaria. Se for de um móvel específico, é melhor registrar como despesa do projeto, assim é descontado da receita desse projeto.',
    pagoDiezmo: 'Sai do que o dízimo tem reservado.',
    aporteCocos: 'Passa do caixa da marcenaria para Cocos.',
    retiroCocos:
      'Sai de Cocos e volta para o caixa da marcenaria: não sai da marcenaria, só muda de bolso.',
    gastoCocos: 'Sai de Cocos e é gasto.',
    gastoTesoro: (tesoro) => `Sai de ${tesoro} e é gasto.`,
    gastoTesoroSinElegir: 'Sai da caixinha que você escolher e é gasto.',
    entreTesoros: (desde, hacia) =>
      `Passa de ${desde} para ${hacia}: o dinheiro não sai, só muda de bolso.`,
    entreTesorosSinElegir:
      'Passa de uma caixinha para outra: o dinheiro não sai, só muda de bolso.',
    elHogarQueda: (saldo) => `A casa fica com ${saldo}.`,
    elHogarQuedaEnNegativo: (saldo) => `A casa fica com ${saldo}, no vermelho.`,
    elTallerQueda: (saldo) => `A marcenaria fica com ${saldo}.`,
    elTallerQuedaEnNegativo: (saldo) => `A marcenaria fica com ${saldo}, no vermelho.`,
    cocosQueda: (saldo) => `Cocos fica com ${saldo}.`,
    cocosQuedaEnNegativo: (saldo) => `Cocos fica com ${saldo}, no vermelho.`,
    cocosQuedaDeLaMeta: (saldo, meta) => `Cocos fica com ${saldo} da meta de ${meta}.`,
    teVanAQuedarPorPagar: (saldo) => `Depois deste pagamento, ainda faltam ${saldo} para pagar.`,
    tePasas: (saldo) => `Com este pagamento, você paga ${saldo} a mais.`,
    quedasAlDia: 'Com este pagamento, você fica em dia.',
    compra: 'Troca pesos por dólares: o dinheiro não sai, só muda de moeda.',
    venta: 'Troca dólares por pesos: o dinheiro não sai, só muda de moeda.',
    quedan: (desde, quedaDesde, hacia, quedaHacia) =>
      `${desde} fica com ${quedaDesde}, e ${hacia} com ${quedaHacia}.`,
    quedanConElPrimeroEnNegativo: (desde, quedaDesde, hacia, quedaHacia) =>
      `${desde} fica com ${quedaDesde}, no vermelho, e ${hacia} com ${quedaHacia}.`,
    ingresoEnDolares:
      'Entra na caixinha em dólares que você escolher, sem passar pela marcenaria nem pelo dízimo.',
    entraA: (tesoro) => `Entra em ${tesoro}, sem passar pela marcenaria nem pelo dízimo.`,
    queda: (tesoro, saldo) => `${tesoro} fica com ${saldo}.`,
    quedaEnNegativo: (tesoro, saldo) => `${tesoro} fica com ${saldo}, no vermelho.`,
  },
  diezmo: {
    debes: 'Você deve',
    debesElImporte: (importe) => `Você deve ${importe}`,
    deLoQueYaCobraste: 'do que você já recebeu e ainda não deu',
    pagasteDeMas: 'Você pagou a mais',
    pagasteElImporteDeMas: (importe) => `Você pagou ${importe} a mais`,
    seDescuenta: 'é descontado do próximo dízimo gerado',
    estasAlDia: 'Você está em dia',
    todoPagado: 'tudo o que foi gerado já está pago',
  },
  resumenDelMes: {
    entroAlHogar: 'Receita da casa',
    gastoElHogar: 'Gastos da casa',
    facturoElTaller: 'Faturamento da marcenaria',
  },
  libro: {
    motivoDelBloqueo: {
      'del-proyecto':
        'Este lançamento é gerado pelo projeto: vem dos recebimentos, das despesas e da divisão que ficou fixada no recebimento. Para mudar, corrija o projeto.',
      ajuste:
        'Um ajuste não pode ser editado: é o registro de uma correção que já foi feita. Se ficou errado, compense com outro ajuste no sentido contrário.',
    },
    etiquetaDerivada: {
      cobro: 'Recebimento do projeto',
      gasto: 'Despesa do projeto',
      diezmo: 'Dízimo da divisão',
      sueldo: 'Pró-labore da divisão',
      fijos: 'Custos fixos da divisão',
      prioridad: 'Etapa da divisão',
      reparto: 'Parte da divisão',
    },
    delTrabajo: 'Do projeto',
    ajusteDeSaldo: 'Ajuste de saldo',
    movimiento: 'Movimentação',
    otroTesoro: 'Outra caixinha',
    yaEstabaEnTusSaldos: 'já estava nos seus saldos',
    sinConfirmar: 'a confirmar',
    sinEfectoEnLosSaldos: 'sem efeito nos saldos',
  },
  ficha: {
    fecha: 'Data',
    saleDe: 'De',
    entraA: 'Para',
    categoria: 'Categoria',
    deAfueraDelTaller: 'fora da marcenaria',
    seVaDelTaller: 'fora da marcenaria',
    yaEnLaApertura:
      'É de antes de você começar a usar o app: esse dinheiro já estava nos seus saldos, então fica registrado com a data, mas não movimenta as caixinhas.',
    editar: 'Editar',
    borrar: 'Excluir',
    verElTrabajo: (titulo) => `Ver “${titulo}”`,
    verElTrabajoSinTitulo: 'Ver o projeto',
  },
  casillaDeLaApertura: 'Esse dinheiro já estava nos seus saldos quando você começou a usar o app',
  cambioEnElLibro: (sale, entra, cotizacion) => `${sale} → ${entra} · a ${cotizacion}`,
  equivalenteDeLaCompra: (pesos, cotizacion, fecha) =>
    `≈ ${pesos} a ${cotizacion}, sua última compra de dólares (${fecha})`,
  equivalenteDeLaVenta: (pesos, cotizacion, fecha) =>
    `≈ ${pesos} a ${cotizacion}, sua última venda de dólares (${fecha})`,
  comprarDolares: 'Comprar dólares',
  venderDolares: 'Vender dólares',
} satisfies Mensajes['movimiento'];
