import type { Mensajes } from '../es';

import { plural } from './plural';

export const paginaProyectos = {
  comun: {
    proyectos: 'Projetos',
    volverAProyectos: 'Voltar para Projetos',
    noEsta: 'Esse projeto não está aqui',
    noEstaTexto:
      'Talvez você tenha excluído em outro dispositivo, ou o link aponta para um projeto de outra marcenaria.',
    mostrarleAlCliente: 'Mostrar ao cliente',
    editar: 'Editar',
    contactarA: (cliente) => `Entrar em contato com ${cliente}`,
    darPorPerdido: 'Marcar como perdido',
    siNoSale: 'Se não sair',
    notas: 'Notas',
    notasEjemplo: 'O que te disseram por telefone, medidas, como chegar…',
    presupuesto: 'Orçamento',
    todaviaSinPresupuesto: 'Ainda sem orçamento',
    senaCobrada: 'Sinal recebido',
    sinSena: 'Sem sinal',
    telefono: 'Telefone',
    sinTelefono: 'Sem telefone',
    estabaEn: 'Estava em',
    cobrado: 'Recebido',
    saldo: 'Saldo',
    sinSaldo: 'Quitado',
    todos: 'Todos',
    buscarPorClienteOTrabajo: 'Buscar por cliente ou projeto',
    limpiarLaBusqueda: 'Limpar a busca',
    fechaYCuando: (fecha, cuando) => `${fecha}, ${cuando}`,
  },
  ficha: {
    fechas: {
      inicio: 'Início',
      listo: 'Pronto',
      entregaEstimada: 'Previsão de entrega',
      entregaComprometida: 'Entrega confirmada',
      entregado: 'Entregue',
      cerrado: 'Fechado',
      cobrado: 'Pago',
    },
    recienAprobado: 'Passou de Consultas para Ativos, com o que você já tinha recebido incluído.',
    cobrarElSaldo: (saldo) => `Receber o saldo de ${saldo}`,
    cobrarYRepartir: 'Receber e dividir',
    pagosRecibidos: 'Pagamentos recebidos',
    cuantosPagos: (pagos) => plural(pagos, { one: '# pagamento', other: '# pagamentos' }),
    sinPagos: 'Você ainda não recebeu nada deste projeto. O sinal costuma vir primeiro.',
    pago: 'Pagamento',
    gastosEInsumos: 'Despesas e insumos',
    cuantosGastos: (gastos) => plural(gastos, { one: '# item', other: '# itens' }),
    sinGastos:
      'Nenhuma despesa registrada. Tudo o que você comprar para este móvel vai aqui e é descontado da receita do projeto.',
    insumo: 'Insumo',
    totalDeGastos: 'Total de despesas',
    cargarPagosYGastos: 'Registrar pagamentos e despesas',
    congelados: {
      cobrado:
        'Este projeto está pago: os pagamentos e as despesas ficaram congelados com a divisão.',
      perdido:
        'Este projeto está perdido: os pagamentos e as despesas ficaram congelados com a divisão.',
    },
    entregaYComprobante: 'Entrega e comprovante',
    direccionDeEntrega: 'Endereço de entrega',
    sinDireccion: 'Sem endereço',
    otraDireccion: 'Diferente do endereço do cliente',
    abrirEnElMapa: 'Abrir no mapa',
    comprobante: 'Comprovante a emitir',
    formaDePago: 'Forma de pagamento',
    sinDefinir: 'Não definido',
    notasDeObra: 'Notas do projeto',
    notasDeObraEjemplo: 'Medidas, o que falta, o que conversar com o cliente…',
  },
  contacto: {
    consultas: 'Consultas',
    sinFecha: 'Sem data',
    vencioEl: (fecha) => `Venceu em ${fecha}`,
    datosDelContacto: 'Dados do contato',
    relevamiento: 'Visita técnica',
    visita: 'Visita técnica',
    cambiarElRelevamiento: 'Mudar a data da visita técnica',
    cambiarLaVisita: 'Mudar a data da visita técnica',
    cambiar: 'Mudar',
    valeHasta: 'Válido até',
    cambiarLaVigencia: 'Mudar até quando o orçamento vale',
    presupuestoAntesDel: 'Orçamento até',
    sinFechaLimite: 'Sem prazo',
    gastosCargados: 'Despesas registradas',
    yaEntroALaCaja:
      'O sinal já entrou no caixa da marcenaria e as despesas já saíram: aparecem no Financeiro desde o dia em que você registrou.',
    cargarOtroPago: 'Registrar outro pagamento ou uma despesa',
    siNoSaleConSena: (sena) =>
      `Se o cliente disse “por enquanto não”, passe para Retornos com o dia em que você vai voltar a escrever: sai das suas consultas e a agenda te avisa. Se não for, o sinal de ${sena} vira receita da marcenaria, e o contato passa para o histórico. Dá para reativar.`,
    siNoSaleSinSena:
      'Se o cliente disse “por enquanto não”, passe para Retornos com o dia em que você vai voltar a escrever: sai das suas consultas e a agenda te avisa. Se não for, passa para o histórico sem mexer em dinheiro. Dá para reativar.',
    porAhoraNo: 'Por enquanto não',
  },
  seguimiento: {
    seguimiento: 'Retornos',
    sinDia: 'Sem dia para voltar a escrever',
    hoy: 'Hoje você volta a escrever',
    leTocaba: (fecha) => `Era para ${fecha}`,
    leVolvesAEscribir: (fecha) => `Você volta a escrever em ${fecha}`,
    proximoContacto: 'Próximo contato',
    registrarElContacto: 'Registrar o contato',
    cuandoLeEscribas:
      'Quando você escrever, registre: aí você escolhe se volta para as consultas, se segue em Retornos com outra data ou se não vai.',
    datosDelTrabajo: 'Dados do projeto',
    historia: 'Histórico de retornos',
    sinHistoria: 'Você ainda não voltou a escrever desde que passou para Retornos.',
    siNoSaleConSena: (sena) =>
      `O sinal de ${sena} vira receita da marcenaria, e o projeto passa para o histórico. Dá para reativar.`,
    siNoSaleSinSena: 'Passa para o histórico sem mexer em dinheiro. Dá para reativar.',
  },
  lista: {
    metricas: {
      proyectos: 'projetos',
      enCurso: 'em andamento',
      entregadosConSaldo: 'entregues com saldo',
      cobrados: 'pagos',
    },
    ordenarPor: 'Ordenar por',
    vacio: {
      activos: {
        titulo: 'Ainda não há projetos ativos',
        detalle:
          'Aqui ficam os projetos que os clientes aprovaram. Os contatos e os orçamentos que esperam resposta ficam em Consultas, e passam sozinhos para esta aba quando você marca a aprovação.',
      },
      historial: {
        titulo: 'Você ainda não fechou nenhum projeto',
        detalle:
          'Quando você receber o primeiro, aqui vai ficar o histórico com o que você ganhou em cada um.',
      },
    },
    cargarUnProyecto: 'Registrar um projeto',
    cargarContacto: 'Registrar contato',
    nuevoProyecto: 'Novo projeto',
    etapa: 'Etapa',
    buscarPorCliente: 'Buscar por cliente',
    ordenar: 'Ordenar',
    ningunoCoincide: (busqueda) => `Nenhum projeto corresponde a “${busqueda}”.`,
    ningunoEnEseEstado: 'Nenhum projeto nesse status.',
  },
  consultas: {
    visita: 'Visita técnica',
    vacioTitulo: 'Nenhuma consulta por enquanto',
    vacioDetalle:
      'Quando alguém ligar, registre aqui com o que a pessoa pede e a data da visita técnica. Se na visita ela deixou um sinal, registre: entra no caixa da marcenaria desde esse dia. Quando aprovar, passa para Ativos.',
    cargarElPrimero: 'Registrar o primeiro contato',
    buscarContacto: 'Buscar contato',
    ningunoCoincide: (busqueda) => `Nenhum contato corresponde a “${busqueda}”.`,
    ningunoEnEsaEtapa: 'Nenhum contato está nessa etapa.',
    orden: 'Primeiro o que espera há mais tempo; as visitas agendadas, no final.',
    contactos: 'Contatos',
  },
  listaDeSeguimiento: {
    sinFecha: 'Sem data para voltar a escrever',
    leTocaHoy: 'É hoje',
    atrasado: (fecha, cuando) => `Atrasado: era para ${fecha}, ${cuando}`,
    elDia: (fecha, cuando) => `${fecha}, ${cuando}`,
    volverAEscribirle: 'Voltar a escrever',
    vacioTitulo: 'Ninguém em Retornos',
    vacioDetalle:
      'Quando uma consulta disser “por enquanto não”, passe para Retornos pela ficha dela com o dia em que você vai voltar a escrever. Aqui eles ficam em ordem, os atrasados primeiro, e a agenda te avisa quando chegar a hora.',
    buscarEnSeguimiento: 'Buscar em Retornos',
    nadieCoincide: (busqueda) => `Ninguém em Retornos corresponde a “${busqueda}”.`,
    orden: 'Pelo dia em que você vai voltar a escrever: os atrasados primeiro.',
    enSeguimiento: 'Em Retornos',
  },
  insumos: {
    insumosDelTrabajo: 'Insumos do projeto',
    insumos: 'Insumos',
    enMaun: 'em Maun até ser recebido',
    entro: 'Entrou',
    gastado: 'Gasto',
    queda: 'Sobra',
    nada: 'Nada',
  },
  analitico: 'Análise das entregas',
  presupuesto: {
    volverAlTrabajo: 'Voltar ao projeto',
    yaNoSeCambia: 'Este orçamento não pode mais ser alterado',
    yaNoSeCambiaTexto:
      'O projeto já foi aprovado ou fechado. O que você enviou fica na ficha, com o PDF.',
  },
  vistaCliente: {
    volverAlTrabajo: 'Voltar ao projeto',
    volverA: (trabajo) => `Voltar para “${trabajo}”`,
    sinSenal: 'Sem internet: isto é o último que carregamos. Pode não estar atualizado.',
    noEsta: 'Esse projeto não está aqui',
    noEstaTexto:
      'Talvez você tenha excluído, ou o link aponta para um projeto de outra marcenaria.',
  },
} satisfies Mensajes['paginaProyectos'];
