import type { Mensajes } from '../es';

import { plural } from './plural';

export const proyecto = {
  estados: {
    contacto: 'Contato',
    presupuesto_estimativo: 'Estimativa enviada',
    relevamiento: 'Visita técnica',
    a_presupuestar: 'A orçar',
    presupuesto_enviado: 'Orçamento enviado',
    en_seguimiento: 'Para retornar',
    perdido: 'Perdido',
    en_curso: 'Em andamento',
    entregado: 'Entregue',
    cobrado: 'Pago',
  },
  formasDePago: {
    efectivo: 'Dinheiro',
    transferencia: 'Transferência',
    cuotas: 'Parcelado',
    mixto: 'Misto',
  },
  comprobantes: {
    factura_a: 'Fatura A',
    factura_b: 'Fatura B',
    factura_c: 'Fatura C',
    remito: 'Nota de entrega',
    sin_comprobante: 'Sem comprovante',
  },
  etapas: {
    consultas: 'Consultas',
    seguimiento: 'Retornos',
    activos: 'Ativos',
    historial: 'Histórico',
  },
  orden: {
    cliente: 'Cliente',
    trabajo: 'Projeto',
    presupuesto: 'Orçamento',
    cobrado: 'Recebido',
    saldo: 'Saldo',
    entrega: 'Entrega',
    estado: 'Status',
  },
  cambios: {
    volverAContacto: 'Voltar para contato',
    mandeUnEstimativo: 'Marcar estimativa como enviada',
    pasarARelevamiento: 'Passar para visita técnica',
    pasarAPresupuestar: 'Começar a orçar',
    mandeElPresupuesto: 'Marcar orçamento como enviado',
    volvioAPresupuesto: 'Voltar para orçamento',
    yaLoAprobo: 'Marcar como aprovado',
    volvioAlTaller: 'Voltar para a marcenaria',
    porAhoraNo: 'Por enquanto não',
    yaLoEntregue: 'Marcar como entregue',
  },
  cobro: {
    instancias: {
      sena: 'Sinal',
      saldo: 'Saldo',
    },
    formas: {
      transferencia: 'Transferência',
      efectivo: 'Dinheiro',
    },
  },
  consultas: {
    irARelevarEl: (fecha) => `Fazer a visita técnica em ${fecha}`,
    visitaDentroDe: (cuando) => `Visita técnica ${cuando}`,
    irARelevarHoy: 'Fazer a visita técnica hoje',
    laVisitaEsHoy: 'A visita técnica é hoje',
    estimativoEnviadoHoy: 'Estimativa enviada hoje',
    estimativoSinRespuesta: (cuando) => `Estimativa enviada ${cuando}, sem resposta`,
    siAvanzaFaltaAgendar: 'Se avançar, falta agendar a visita técnica',
    yaPagoLaVisita: 'Já pagou a visita técnica: falta orçar',
    faltaQueApruebeElEstimativo: 'Falta o cliente aprovar a estimativa e pagar a visita técnica',
    faltaPonerleFecha: 'Falta marcar a data da visita técnica',
    relevamientoSinFecha: (cuando) => `Último contato ${cuando}, sem data de visita técnica`,
    faltaPasarLoRelevado: 'Falta passar a visita técnica para orçamento',
    laVisitaFue: (cuando) => `A visita técnica foi ${cuando}`,
    aPresupuestarDesde: (cuando) => `Orçamento pendente, último contato ${cuando}`,
    yaEstaArmado: 'Já está pronto: falta enviar o orçamento',
    faltaPresupuestarConTareas: (hechas, total) =>
      `Falta orçar: ${String(hechas)} de ${String(total)} tarefas feitas`,
    faltaPresupuestar: 'Falta orçar',
    faltaElEstimativo: 'Falta a estimativa: a visita técnica não foi paga',
    vencioElPresupuesto: 'O orçamento venceu: atualize ou mude a data',
    valiaHasta: (fecha) => `Valia até ${fecha}`,
    faltaLlamar: 'Falta ligar para saber',
    presupuestoEnviadoHoy: 'Orçamento enviado hoje',
    presupuestoSinRespuesta: (cuando) => `Orçamento enviado ${cuando}, sem resposta`,
    faltaAgendarLaVisita: 'Falta agendar a visita técnica',
    contactoSinVisita: (cuando) => `Último contato ${cuando}, sem visita técnica agendada`,
    pasos: {
      yaLoAprobo: 'Marcar como aprovado',
      yaFuiARelevar: 'Marcar visita técnica como feita',
      mandeElPresupuesto: 'Marcar orçamento como enviado',
      agendarLaVisita: 'Agendar visita técnica',
      mandeUnEstimativo: 'Marcar estimativa como enviada',
      mandeElEstimativo: 'Marcar estimativa como enviada',
      pasarAPresupuestar: 'Começar a orçar',
      loAproboPasarAProyectos: 'Aprovado: passar para Projetos',
      seguirArmandolo: 'Continuar o orçamento',
      armarElPresupuesto: 'Montar o orçamento',
    },
  },
  corte: {
    sinCorte: (mes) =>
      `${mes} ainda não foi dividido. Quando você fechar um projeto, aqui vai aparecer para onde vai cada peso.`,
    sinNadaCobrado: (trabajos, mes) =>
      `${plural(trabajos, { one: 'Um projeto fechado', other: '# projetos fechados' })} em ${mes}, sem nada recebido: não houve nada para dividir.`,
    sinIngreso: (trabajos, mes) =>
      `${plural(trabajos, { one: 'Um projeto fechado', other: '# projetos fechados' })} em ${mes}, e as despesas consumiram o que foi recebido: não sobrou receita para dividir.`,
    repartido: (trabajos, mes, partes) =>
      `${plural(trabajos, { one: 'Um projeto fechado', other: '# projetos fechados' })} em ${mes}: ${partes}.`,
    repartidoConGastos: (trabajos, mes, partes) =>
      `${plural(trabajos, { one: 'Um projeto fechado', other: '# projetos fechados' })} em ${mes}: ${partes}. O resto foram despesas.`,
    alHogar: (parte) => `${parte} para a casa`,
    alTaller: (parte) => `${parte} para a marcenaria`,
    alDiezmo: (parte) => `${parte} para o dízimo`,
    aOtroTesoro: (parte, tesoro) => `${parte} para ${tesoro}`,
    menosDelUno: 'menos de 1%',
    gastos: 'Despesas',
  },
  tesoroSinNombre: 'Caixinha',
  costos: {
    madera: 'Madeira',
    herrajes: 'Ferragens',
    flete: 'Frete',
    ayudante: 'Ajudante',
    otro: 'Outro',
  },
  despiece: {
    clases: {
      sueldo: 'Pró-labore',
      fijos: 'Custos fixos',
      prioridad: 'Reserva fixa',
    },
    topeDelMes: 'Teto do mês',
    diezmo: (porcentaje) => `Dízimo ${porcentaje}%`,
    diezmoSobreLoCobrado: (porcentaje) => `Dízimo ${porcentaje}% sobre o que você recebe`,
    diezmoSobreElIngreso: (porcentaje) => `Dízimo ${porcentaje}% sobre a receita`,
    obligacion: (tesoro, porcentaje) => `${tesoro} ${porcentaje}%`,
    obligacionSobreLoCobrado: (tesoro, porcentaje) =>
      `${tesoro} ${porcentaje}% sobre o que você recebe`,
    obligacionSobreElIngreso: (tesoro, porcentaje) => `${tesoro} ${porcentaje}% sobre a receita`,
    deLoQueSobra: (porcentaje) => `${porcentaje}% do que sobra`,
    elResto: 'O resto',
  },
  distribucion: {
    titulo: 'Divisão da receita',
    grupos: {
      obligacion: 'Obrigações',
      compromiso: 'Contas',
      ahorro: 'Reservas',
      superavit: 'Superávit',
    },
    resto: 'Resto',
    aTesoro: (tesoro) => `para ${tesoro}`,
    detalle: (etiqueta, monto) => `${etiqueta}: ${monto}`,
    detalleATesoro: (etiqueta, tesoro, monto) => `${etiqueta} para ${tesoro}: ${monto}`,
    faltan: (monto) => `faltam ${monto}`,
    cubierto: 'já coberto por outros recebimentos do mês',
    conSuSaldo: 'já tem o valor',
    llegaALaMeta: 'atingiu a meta',
    cobradosMenosGastos: (cobrado, gastos) => `${cobrado} recebidos menos ${gastos} de despesas`,
    ingreso: 'Receita',
    sinCobrar:
      'Ainda não entrou dinheiro deste projeto. Quando for recebido, aqui você vê como a receita desce pela fila das caixinhas.',
    sinIngreso:
      'As despesas consumiram o que foi recebido: não há receita para dividir, e o prejuízo fica no caixa da marcenaria.',
    proyeccion:
      'Projeção sobre o que foi recebido até hoje, com a fila das caixinhas. A divisão se torna efetiva quando o projeto for recebido.',
    provisoria:
      'O servidor ainda não confirmou esta divisão: é a que vai ficar se nada mudou do outro lado. Ela se confirma sozinha quando a internet voltar.',
  },
  entrega: {
    franjas: {
      manana: 'de manhã',
      tarde: 'à tarde',
    },
    conFranja: {
      manana: (dia) => `${dia}, de manhã`,
      tarde: (dia) => `${dia}, à tarde`,
    },
    vencida: (cuando) => `venceu ${cuando}`,
    venceHoy: 'vence hoje',
    venceManana: 'vence amanhã',
    enDias: (dias) => plural(dias, { one: 'em # dia', other: 'em # dias' }),
    comprometida: 'confirmada',
    sinFecha: 'Sem data',
    conFranjaComprometida: (fecha) => `${fecha} · confirmada`,
  },
  formulario: {
    sinMonto: 'Informe o valor, em pesos.',
    demasiadoLargo: (maximo) =>
      plural(maximo, {
        one: 'Não pode passar de # caractere.',
        other: 'Não pode passar de # caracteres.',
      }),
    sinFecha: 'Informe a data.',
    sinCliente: 'Escolha um cliente ou crie um novo aqui.',
    sinTitulo: 'Diga qual é o móvel.',
    presupuestoNegativo: 'Confira o orçamento: é em pesos.',
    presupuestoNegativoEnDolares: 'Confira o orçamento: é em dólares.',
    sinMontoEnDolares: 'Informe o valor, em dólares.',
    senaFueraDeRango: 'O sinal vai de 0 a 100.',
  },
  insumos: {
    tallerPuso: (monto) => `A marcenaria colocou ${monto}.`,
    enOtroTesoro: (monto, tesoro) => `Além disso, ${monto} deste projeto estão em “${tesoro}”.`,
  },
  plata: {
    conSuValorEnPesos: (loQueSePago, enPesos) => `${loQueSePago} (${enPesos})`,
  },
  pago: {
    tePago: 'O cliente pagou',
    pasarADolares: 'Mudar para dólares',
    pasarAPesos: 'Mudar para pesos',
    ayudaDelDolar: {
      pesosDeUnTrabajoEnDolares: 'O dólar do dia do pagamento, como diz o seu orçamento.',
      dolaresDeUnTrabajoEnPesos: 'O que você combinou com o cliente nesse dia.',
      dolaresDeUnTrabajoEnDolares: 'Quantos pesos cada dólar vale na divisão.',
    },
    entraA: 'Vai para',
    entraAlTesoro: (nombre) => `Vai para “${nombre}”.`,
    entraAMaun: 'Vai para o caixa da marcenaria.',
    sinTesoroEnDolares:
      'Um pagamento em dólares vai para uma caixinha em dólares, e você ainda não tem nenhuma.',
    crearUnTesoroEnDolares: 'Criar uma caixinha em dólares',
    elegiElTesoro: 'Escolha para qual caixinha em dólares vai.',
    descuenta: (monto) => `Abate ${monto} do preço.`,
    vale: (monto) => `Vale ${monto} na divisão.`,
    descontoConElDolar: (monto, dolar) => `Abateu ${monto} do preço, com o dólar a ${dolar}.`,
    valioConElDolar: (monto, dolar) => `Valeu ${monto} na divisão, com o dólar a ${dolar}.`,
  },
  liquidacion: {
    operaciones: {
      cobro: 'Recebimento',
      cierre: 'Fechamento como perdido',
      reapertura: 'Reabertura do recebimento',
      reactivacion: 'Reativação do orçamento',
    },
    elRepartoSalioDistinto: 'A divisão saiu diferente da que você viu.',
    diferencia: (tesoro, esperado, quedo) =>
      `${tesoro}: você esperava ${esperado} e ficou em ${quedo}.`,
    diferenciaPorLoQueTenia: (tesoro, esperado, quedo, tenia) =>
      `${tesoro}: você esperava ${esperado} e ficou em ${quedo}, porque já tinha ${tenia}.`,
    diferenciaPorElMes: (tesoro, esperado, quedo, llevaba) =>
      `${tesoro}: você esperava ${esperado} e ficou em ${quedo}, porque o mês já tinha ${llevaba} de outro projeto.`,
    quedoEnElTaller: (quedo, esperado) =>
      `A diferença ficou na marcenaria: ${quedo} em vez de ${esperado}.`,
    quedoEnElRemanente: (quedo, esperado) =>
      `A diferença ficou na sobra da marcenaria: ${quedo} em vez de ${esperado}.`,
    escalones: {
      sueldo: 'Pró-labore',
      fijos: 'Custos fixos',
    },
  },
  marca: {
    enPausa: {
      cobro: 'Pago, aguardando confirmação',
      cierre: 'Fechado, aguardando confirmação',
      reapertura: 'Reaberto, aguardando confirmação',
      reactivacion: 'Reativado, aguardando confirmação',
    },
    confirmando: {
      cobro: 'Confirmando o recebimento…',
      cierre: 'Confirmando o fechamento…',
      reapertura: 'Confirmando a reabertura…',
      reactivacion: 'Confirmando a reativação…',
    },
    rechazado: 'O servidor recusou',
  },
  listo: 'Pronto',
  necesidades: {
    material: {
      titulo: 'Materiais necessários',
      agregar: 'Adicionar material',
      campo: 'Qual material falta',
      cuantos: 'Quantidade de material',
      placeholder: 'Chapas de melamina, tábua, laca…',
      ayuda: 'O que é preciso comprar ou encomendar: cortes, tábuas, tinta. A medida vai no nome.',
      casilla: (necesidad) => `Pronto: ${necesidad}`,
      cuantosListos: (listos, total) => `${String(listos)} de ${String(total)} prontos`,
    },
    herraje: {
      titulo: 'Ferragens necessárias',
      agregar: 'Adicionar ferragem',
      campo: 'Qual ferragem falta',
      cuantos: 'Quantidade de ferragens',
      placeholder: 'Dobradiças, pistões, puxadores…',
      ayuda: 'O que é preciso pedir para este projeto. A quantidade é opcional.',
      casilla: (necesidad) => `Pronta: ${necesidad}`,
      cuantosListos: (listos, total) => `${String(listos)} de ${String(total)} prontas`,
    },
    herramienta: {
      titulo: 'Ferramentas necessárias',
      agregar: 'Adicionar ferramenta',
      campo: 'Qual ferramenta falta',
      cuantos: 'Quantidade de ferramentas',
      placeholder: 'Serra circular, lixadeira de cinta…',
      ayuda: 'O que é preciso ter à mão no dia em que você fizer. A quantidade é opcional.',
      casilla: (necesidad) => `Pronta: ${necesidad}`,
      cuantosListos: (listos, total) => `${String(listos)} de ${String(total)} prontas`,
    },
  },
  obra: {
    faltaEntregarlo: 'Falta entregar',
    entregaComprometida: (fecha, cuando) => `Entrega confirmada: ${fecha} (${cuando})`,
    faltaAcordarLaEntrega: 'Falta combinar a entrega',
    listoDesde: (fecha) => `Pronto desde ${fecha}`,
    sinEntregaEstimada: 'Sem previsão de entrega',
    entregaEstimada: (cuando) => `Previsão de entrega: ${cuando}`,
    faltaCobrar: (saldo) => `Falta receber ${saldo}`,
    faltaCobrarloYRepartir: 'Falta receber e dividir',
    entregadoSinFecha: 'Entregue, sem data de entrega',
    entregadoEl: (fecha) => `Entregue em ${fecha}`,
  },
  clienteBorrado: 'Cliente excluído',
  resultadosDelContacto: {
    reactivado: 'Voltou para as consultas',
    perdido: 'Marcado como perdido',
    otra_fecha: 'Seguiu em Retornos com outra data',
  },
  tareas: {
    etiquetas: {
      presupuesto_diseno: 'Desenhar',
      presupuesto_despiece: 'Fazer o plano de corte',
      presupuesto_cotizacion: 'Cotar os materiais',
      presupuesto_pdf: 'Montar o orçamento',
    },
    detalleDeCotizar: 'Madeira e ferragens, frete, ajudante',
  },
  tiposDeArranque: {
    cocina: 'Cozinha',
    placard: 'Guarda-roupa',
    vestidor: 'Closet',
    vanitory: 'Gabinete de banheiro',
    muebleDeTv: 'Rack de TV',
    biblioteca: 'Estante de livros',
    escritorio: 'Escrivaninha',
  },
  sena: {
    titulo: 'Sinal para confirmar',
    sinPresupuesto:
      'Ainda não há orçamento, então não há sinal para calcular. Registre o orçamento ou marque a opção que o cliente aprovou.',
    delTrabajo: (porcentaje) => `${porcentaje}% do orçamento, deste projeto`,
    delTaller: (porcentaje) => `${porcentaje}% do orçamento, padrão da marcenaria`,
    sena: 'Sinal',
    cobrado: 'Recebido',
    falta: 'Falta',
    nada: 'Nada',
    cubiertaDeMas: (deMas) => `O sinal já está coberto, e você recebeu ${deMas} a mais.`,
    cubierta: 'O sinal já está coberto.',
  },
  costosDeCotizar: {
    titulo: 'Custos estimados',
    ayuda:
      'O que você calcula que vai gastar. Não mexe no orçamento: esse você define, com a receita que quer que ele deixe.',
    cargadas: (cargadas, total) => `${String(cargadas)} de ${String(total)}`,
    sinEstimar: 'Sem estimativa',
    costoEstimado: 'Custo estimado',
    sinPresupuesto: 'Quando o projeto tiver orçamento, aqui aparece o que sobra para você.',
    presupuesto: 'Orçamento',
    teQuedaSiTeLoAprueban: 'Sobra, se aprovarem',
    teQueda: 'Sobra',
    enContra: 'Você está estimando mais custo do que o orçamento.',
    dolarParaLosCostos: 'Dólar para os custos',
    ayudaDelDolar: 'Os custos ficam em pesos: com esse dólar você também vê e digita em dólares.',
    faltaElDolar: 'Informe o dólar para os custos e aqui aparece o que sobra, em dólares.',
    aproximado: (monto) => `≈ ${monto}`,
  },
  conceptosDeSiempre: {
    senaDeLaVisita: 'Sinal da visita',
    senaAlAprobar: 'Sinal',
    saldoFinal: 'Saldo final na entrega',
  },
  liquidacionesSinConfirmar: {
    unProyecto: 'Um projeto',
    cuentan: (liquidaciones) =>
      plural(liquidaciones, {
        one: 'Estes saldos contam um acerto que o servidor ainda não confirmou:',
        other: 'Estes saldos contam # acertos que o servidor ainda não confirmou:',
      }),
  },
} satisfies Mensajes['proyecto'];
