import { StyleSheet } from '@react-pdf/renderer';

import { ASCENDENTE, COLOR, CUERPO, HILO, INTERLINEADO, LETRA_MAS_CHICA, MARGEN } from '../medidas';

export const LADO_DEL_QR = 80;

export const ESTILOS_DE_LA_FACTURA = StyleSheet.create({
  pagina: { paddingBottom: 150 },
  codigo: {
    marginTop: 6,
    fontSize: LETRA_MAS_CHICA,
    lineHeight: 1.3,
    fontWeight: 600,
    letterSpacing: 0.3,
    textAlign: 'center',
  },
  rotuloDatos: {
    paddingHorizontal: 6,
    paddingTop: 5,
    paddingBottom: 6,
    borderTopWidth: HILO,
    borderTopColor: COLOR.ink,
  },
  rotuloDato: { fontSize: 9, lineHeight: 1.4 },
  receptor: {
    flexDirection: 'row',
    marginTop: 18,
    borderTopWidth: HILO,
    borderTopColor: COLOR.ink,
    borderBottomWidth: HILO,
    borderBottomColor: COLOR.ink,
  },
  anula: { fontSize: CUERPO, lineHeight: INTERLINEADO, fontWeight: 600 },
  tabla: { marginTop: 20, borderTopWidth: HILO, borderTopColor: COLOR.ink },
  tablaFila: { flexDirection: 'row', paddingVertical: 7 },
  tablaFilaConFilete: { borderTopWidth: HILO, borderTopColor: COLOR.border },
  colDescripcion: { flexGrow: 1, flexBasis: 0, paddingRight: 12 },
  colCantidad: { width: 40, alignItems: 'flex-end' },
  colPrecio: { width: 104, alignItems: 'flex-end' },
  colImporte: { width: 104, alignItems: 'flex-end' },
  total: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 14,
    paddingTop: 12,
    paddingBottom: 11,
    paddingHorizontal: 16,
    backgroundColor: COLOR.mesa,
    borderRadius: 8,
  },
  totalEtiqueta: {
    fontSize: 12,
    lineHeight: 1.3,
    fontWeight: 600,
    marginTop: (20 - 12) * ASCENDENTE,
  },
  totalMonto: { fontSize: 20, lineHeight: 1.1, fontWeight: 600 },
  autorizacion: {
    position: 'absolute',
    left: MARGEN,
    right: MARGEN,
    bottom: 40,
    flexDirection: 'row',
    alignItems: 'center',
    paddingTop: 12,
    borderTopWidth: HILO,
    borderTopColor: COLOR.border,
  },
  qr: { width: LADO_DEL_QR, height: LADO_DEL_QR },
  autorizacionTextos: { marginLeft: 16, flexGrow: 1, flexBasis: 0 },
  autorizacionFuerte: { fontSize: CUERPO, lineHeight: INTERLINEADO, fontWeight: 600 },
  autorizacionDato: { fontSize: CUERPO, lineHeight: INTERLINEADO },
  autorizacionNota: { fontSize: 9, lineHeight: 1.4, color: COLOR.text2, marginTop: 2 },
  marcaDePrueba: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    alignItems: 'center',
    justifyContent: 'center',
  },
  marcaDePruebaTexto: {
    width: 820,
    flexShrink: 0,
    fontSize: 44,
    fontWeight: 600,
    letterSpacing: 2.6,
    textAlign: 'center',
    color: COLOR.ink,
    opacity: 0.08,
    transform: 'rotate(-35deg)',
  },
});
